### ISSUE TITLE
right buttoon of mouse can't trick an event on mac

### ISSUE THREAD

**Issue by DabbyCHEN** [Robbendebiene/Gesturefy#204] opened 2017-12-07 08:30 UTC
I make some finger gestures of mouse click, which can work on left click of mouse but can't work on right click!

**Comment by Itchiii** [comment] 2017-12-09 16:25
In Firefox 57 it is a known bug. Look here: #1 #104 #88 #70 
But you can use the latest version of Firefox 58 (Firefox 58.b7+). 

And please read the addon description or the [CONTRIBUTING.md](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md) before you open an issue. 
> MacOS & Linux users can only use the right mouse button using the latest Firefox 58!

> [Right mouse button is not working on Linux and MacOS](https://github.com/Robbendebiene/Gesturefy/issues/1)

**Comment by Robbendebiene** [comment] 2017-12-10 22:52
Duplicate of #1

**Closed by Robbendebiene** 2017-12-10 22:52 UTC
Labels: duplicate
