### ISSUE TITLE
Feature request: arbitrary start gesture/end of gesture defines action

### ISSUE THREAD

**Issue by LupinIII** [Robbendebiene/Gesturefy#311] opened 2018-07-29 11:39 UTC
I'm still using FF56, because the mozilla forced "webext only" pretty much made the newer FF versions pointless to use for me (might as well use Chrome, because what's the difference?). One of the reasons for not switching are mouse gestures which are much more powerful in the "older" versions.

That said, I'm using FF61 to test addons, like this one, all the time. One of the functions I use in "Mouse gestures suite" in FF56 is opening all links I moved the mouse over while doing a gesture in a new tab. In that addon it works by defining an arbitrary start gesture, like X-U-L-R (imagine drawing a "T" at the end of the gesture). It would be nice, if this extension could support gestures like that.

**Comment by Robbendebiene** [comment] 2018-07-29 20:32
>  (might as well use Chrome, because what's the difference?). 

The fact that you are still searching for add-ons in Firefox proofs to me that there is a reason to prefer Firefox instead of chrome :) And even if you really mean it I can at least tell you, that Mozilla is working on new APIs to allow new and better extensions in contrast to chrome or other browsers.

>  opening all links I moved the mouse over while doing a gesture in a new tab.

Your feature request was already made here: https://github.com/Robbendebiene/Gesturefy/issues/298 and therefore is on the list.

**Comment by Robbendebiene** [comment] 2018-08-09 20:37
Duplicate of  #298

**Closed by Robbendebiene** 2018-08-09 20:37 UTC
Labels: duplicate
