### ISSUE TITLE
Search popup

### ISSUE THREAD

**Issue by kabbill** [Robbendebiene/Gesturefy#149] opened 2017-11-20 10:09 UTC
Is it possible for selected text search to pop up firefox intalled search machines to select? Like many more, I do not use just one search machine in firefox.

**Comment by Robbendebiene** [comment] 2017-11-20 10:59
It's on the list, please follow this issue: https://github.com/Robbendebiene/Gesturefy/issues/89

**Comment by Robbendebiene** [comment] 2017-11-29 14:51
Duplicate of #89

**Closed by Robbendebiene** 2017-11-29 14:51 UTC
Labels: duplicate
