### ISSUE TITLE
Eclectic program for Linux user

### ISSUE THREAD

**Issue by HeJiaJunPan** [Robbendebiene/Gesturefy#126] opened 2017-11-18 12:45 UTC
Right-click with the mouse completely unable to work, it is better to double-click the right mouse button to display the context menu.Allow users to choose whether to spend more time on another behavior for their own habits

**Comment by stmr** [comment] 2017-11-21 12:50
see #1

**Comment by Robbendebiene** [comment] 2017-11-21 23:18
Duplicate of #1

**Closed** 2017-11-21 23:18 UTC
Labels: duplicate
