### ISSUE TITLE
Not able to assign new commands

### ISSUE THREAD

**Issue by thebjorn** [Robbendebiene/Gesturefy#478] opened 2020-06-06 13:41 UTC
### Describe your matter in detail

Same as #472, but details on error message when trying to assign a command.

### Screenshots or further assistance
![gesturify-300](https://user-images.githubusercontent.com/1193143/83945595-0f6b8500-a80c-11ea-8ed0-774f2db8a633.png)

### Your System
- Operating system: win10
- Firefox version: 77.0.1 (64-bit)
- Gesturefy version: 3.0.0

**Comment by thebjorn** [comment] 2020-06-06 13:44
Probably more useful with the line numbers ;-)
![gesturefy-478](https://user-images.githubusercontent.com/1193143/83945669-8bfe6380-a80c-11ea-9a74-39ce5eb2326c.png)

**Comment by thebjorn** [comment] 2020-06-06 13:49
`getName().name.name`?
![gesturefy-478-c](https://user-images.githubusercontent.com/1193143/83945784-4b531a00-a80d-11ea-8e04-737a89703fa9.png)

**Comment by elmo40** [comment] 2020-06-06 16:20
Are you coming from the most recent update or a new install?
I noticed when it updated all my old gestures were drawn but they did not work. I removed them all and remade them all and then they worked.

**Comment by thebjorn** [comment] 2020-06-06 16:39
Thank @elmo40, that worked.  Good thing I only use 4 gestures :-D

**Comment by Robbendebiene** [comment] 2020-06-06 22:20
For the next 2 days I'm unable to read all the bug report. For users who have problems with their settings please look here: https://github.com/Robbendebiene/Gesturefy/issues/480
Sorry for the inconvenience.

**Comment by thebjorn** [comment] 2020-06-06 23:02
@Robbendebiene Thanks for a great extension, I was lost when it stopped working..  Deleting all gestures and recreating the ones I use fixed it for me. 

Feel free to close this issue.

**Comment by Itchiii** [comment] 2020-06-08 15:46
Duplicate of #472

**Closed by Itchiii** 2020-06-08 15:46 UTC
