### ISSUE TITLE
Gestures not working with privacy.resistFingerprinting = true

### ISSUE THREAD

**Issue by ksolheim** [Robbendebiene/Gesturefy#273] opened 2018-03-26 07:36 UTC
Gesturefy 1.2.1 - Firefox 60.0b6 (64-bit) - Windows 7

When attempting to perform a gesture (on any page) it snaps to the top left corner and refuses to move any further.
I've tried resetting the Gesturefy config and disabling all other addons, none made any difference.

Reverting to 1.2.0 fixes the issues. 
![gesturefy121](https://user-images.githubusercontent.com/10515447/37892695-33e6bae8-30c8-11e8-9a94-b3cb548fef4b.png)

**Comment by Robbendebiene** [comment] 2018-03-26 07:45
Thanks for the info, unfortunately it's working for me fine on Firefox 60. Does this also happen if you make a clean install of Gesturefy 1.2.1?

**Comment by ksolheim** [comment] 2018-03-26 08:43
I've tried the following: 
1. Remove Gesturefy 1.2.1
2. Restart Firefox.
3. Install Gesturefy 1.2. 

This did not help. 

However I tried 'Refresh Firefox...' and afterwards 1.2.1 installs and works as intended.

**Comment by Robbendebiene** [comment] 2018-03-26 08:51
Thanks for the info.
Seems like a Firefox related problem. Hopefully this was a unique case.

**Comment by Robbendebiene** [comment] 2018-03-26 10:39
The problem seems to be the about:config setting: `privacy.resistFingerprinting`

**Comment by je-nix** [comment] 2018-03-26 11:22
I can confirm this issue (Arch Linux, Xorg, i3 WM, Firefox 59.0.1) and that <code>privacy.resistFingerprinting</code> causes it. When I set it to false, Gesturefy 1.2.1 works as intended. If set to true, all gestures start at the top left corner of the window, making it impossible (or at least very hard) to draw any commands. After reverting back to 1.2.0 all is well again.
Since I want to keep this setting enabled, I hope that you will find a solution for this issue. Thanks.

**Comment by Robbendebiene** [comment] 2018-03-30 22:25
**To give a little update on this topic:** I asked the Mozilla community about their opinion on this problem and they kindly agreed that addons should not be affected by this setting. They plan to change the behaviour, which will fix the encountered problems. ([more information here](https://bugzilla.mozilla.org/show_bug.cgi?id=1448848))

**Comment by ldgbc** [comment] 2018-07-13 11:46
Those Mozilla guy still haven't fixed this?!

**Comment by Robbendebiene** [comment] 2018-07-13 13:47
> Did they fixed it?

@ldgbc No, it's still not assigned to a developer.

**Comment by sbstn87** [comment] 2018-11-03 15:20
Any updates on the issue? 

BTW, I am still using version 1.2.0 of Gesturefy - that version works when using privacy.resistFingerprinting is set to True. What has changed in 1.2.1 and later version that prevents it from working correctly?

**Comment by xuzhen** [comment] 2018-12-07 15:40
Why not use clientX/clientY instead of screenX/screenY like [Foxy Gestures](https://github.com/marklieberman/foxygestures)?

**Comment by Symbai** [comment] 2020-01-27 11:52
There is also `Mouse Gesture Events` addon which works when `privacy.resistFingerprinting=true` it also works if the site you are visiting has restricted (javascript) access. It seems to use a completely different approach than Gesturefy and Foxy Gesture addon. It's source code is https://iloe.ru/gestures/source-code/ if someone who is able to read it wants to take a look. Maybe its approach can be adopted?

**Comment by Robbendebiene** [comment] 2020-01-27 12:21
The fix for this problem is already coded, but it will be released together with version 3.

> it also works if the site you are visiting has restricted (javascript) access.

Can you further explain what you mean by that?

**Comment by Symbai** [comment] 2020-01-27 12:27
@Robbendebiene Using Gesturefy or Foxy Gesture I often have the problem that mouse gestures are no longer recognized for certain tabs. Previously I was using Mouse Gesture Events and it always worked (except of Firefox pages (addons, settings etc) but that's normal).

I was reading these addons inject code into the site I am visiting. So my thought was that because I am using noscript and other addons, the injected code will not work then.

**Comment by Robbendebiene** [comment] 2020-01-27 12:38
@Symbai I can not explain why Gesturefy stops working for you, but all gesture add-ons have to inject code into the website you visit (including Mouse Gesture Events). I also doubt that Noscript is able to block code injected by add-ons. However there might be other extensions related to mouse events that lead to problems with Gesturefy.

If your problem occurs repeatedly and you can detect some sort of pattern feel free to open an issue for that.

**Closed** 2020-05-12 10:58 UTC
Labels: external
