### ISSUE TITLE
saving pictures and remember last folder

### ISSUE THREAD

**Issue by lpslp** [Robbendebiene/Gesturefy#460] opened 2020-05-02 22:21 UTC
### Describe your matter in detail
steps to reproduce the issue
1- on function "save picture as..." by right clicking i put thru Gesturefy "right mouse button + move right"
2-open any site and save picture by right click on it and "save picture as..." chouse DIR and save. Try it second time - and firefox remember folder where it save pic last time and you appear in this folder.
3-save picture thru Gesturefy as in N1 in some dir. And if you try save pic another time Gesturefy in default download directory and do not remember where you save picture last time.

### Your System
- Operating system:Windows 10x64 1909
- Firefox version:75.0
- Gesturefy version:2.1.6

**Comment by Robbendebiene** [comment] 2020-05-04 09:39
This is a known problem and has already been discussed here: https://github.com/Robbendebiene/Gesturefy/issues/145 To keep things short: This problem cannot be solved and should rather be reported to https://bugzilla.mozilla.org/home

**Comment by lpslp** [comment] 2020-05-04 11:13
you here https://github.com/Robbendebiene/Gesturefy/issues/145#issuecomment-345697772 write _neither in chrome nor in firefox_ but in chrome with https://chrome.google.com/webstore/detail/smartup-gestures/bgjfekefhjemchdeigphccilhncnjldn?hl=ru it remember last folder ...

**Comment by Robbendebiene** [comment] 2020-05-04 13:02
What I meant was, that you cannot set the download location to a destination outside of the download folder. This applies to Firefox and Chrome. However if I do not set the path then Chrome and Firefox behave differently. Chrome remembers your last location, Firefox does not. I can only repeat my self:

> 
> If you want this feature to happen you need to open a feature request/bug on bugzilla.
> You could name the ticket like this: Webextensions download API "save as" preference should open the last directory if not specified
> 
> Btw it's always good to mention that Chrome already behaves like this :)

**Comment by lpslp** [comment] 2020-05-04 13:52
sadly that you from 2017 not open request/bug on bugzilla...

done https://bugzilla.mozilla.org/show_bug.cgi?id=1635120

**Comment by Robbendebiene** [comment] 2020-05-04 13:54
Duplicate of #145

**Closed by Robbendebiene** 2020-05-04 13:54 UTC
Labels: duplicate
