### ISSUE TITLE
Doesn't work for moz-extension://

### ISSUE THREAD

**Issue by rhazor** [Robbendebiene/Gesturefy#94] opened 2017-11-15 12:34 UTC
E.g. addons like https://addons.mozilla.org/en-US/firefox/addon/twitch_5/ open live twitch streams on moz-extension:// tabs and right-click hold + mouse wheel up/down through tabs does not work.

**Comment by rhazor** [comment] 2017-11-15 12:36
update: actually doesn't work when mouse over video screen. Works on regular video players like YouTube or original Twitch tho. Works if mouse over chat window.

So still something is causing it not working on video.

**Comment by rhazor** [comment] 2017-11-15 12:36
update: actually doesn't work when mouse over video screen. Works on regular video players like YouTube or original Twitch tho. Works if mouse over chat window.

So still something is causing it not working on video.

Test it with Twitch 5 installed and on any live channel at https://www.twitch.tv/

**Comment by Robbendebiene** [comment] 2017-11-15 13:08
This is a known API limitation stated in the addon [description](https://addons.mozilla.org/firefox/addon/gesturefy/). Addons are restricted to normal webpages and therefore can not run on most about: pages or pages provided by addons/extensions.

**Comment by rhazor** [comment] 2017-11-15 13:11
> The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

The `https://addons.mozilla.org (for further information see this bug)` part is fixed. Set "privacy.resistFingerprinting.block_mozAddonManager" to True.

Like I said it works partially on moz-extension:// pages, it just doesn't work while mouse over video player overlay.

**Comment by Robbendebiene** [comment] 2017-11-15 13:27
I tested Twitch5 on FF58 and for me it's not working on the chat window. It might work because its an iframe (which means the page is loading and including another webpage) but the main page which contains the video player is provided by the extension and not included via iframe.

**Comment by snodo** [comment] 2017-11-21 08:17
That's exactly what I wanted to ask for.

It's really annoying that I can start a new tab by gesture but cannot:
1. close the "about:newtab" page (happens often that I notice I don't need a new tab yet)
2. change to the left/right tab

**Comment by Robbendebiene** [comment] 2017-11-21 11:35
@snodo I recommend using something like https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/. If you set your new tab page to a normal website, everything will work fine.

**Comment by snodo** [comment] 2017-11-21 13:07
Good idea! Thank you - that helps me a lot.

**Comment by Robbendebiene** [comment] 2017-12-01 13:48
Duplicate of #5

**Closed by Robbendebiene** 2017-12-01 13:48 UTC
Labels: api limitation
