### ISSUE TITLE
Gesture end opens underlying links when using middle button

### ISSUE THREAD

**Issue by kkurola** [Robbendebiene/Gesturefy#479] opened 2020-06-06 15:11 UTC
### Describe your matter in detail
Gesture termination does not prevent the default event handling when button is released. I have middle mouse button as a trigger which normally opens a link in a new tab. If a gesture happens to end above a link it will end up running both the gesture action and opening the link in new tab.

At least a successful gesture should prevent this double action, but in my case it would make sense to also fix also aborted gestures that timed out.  If I'm waiting to cancel a gesture it is very unlikely I would like to open any links when releasing the button.

To reproduce:
1. Press middle button to activate gesture drawing
2. Draw the gesture making sure the end point is on a link (in my case up + down which closes the tab)
3. Release middle button
4. Action is run (current tab closes), a new tab of the link is opened

### Your System
- Operating system: Windows 10
- Firefox version: 77.0.1
- Gesturefy version: 3.0.0

**Comment by Robbendebiene** [comment] 2020-06-06 22:38
Thanks for the report.
From my testing the start **and** the end point of the gesture has to be the link in order to open the link in a new tab. Can you confirm this?

I'll try to fix this as soon as possible.

**Comment by kkurola** [comment] 2020-06-07 19:36
Yes, that seems to be the case. I didn't notice the difference initially as my up-down gesture naturally starts and ends on on the same spot. Thanks for the quick reply!

**Comment by jefferysmall** [comment] 2020-06-09 19:41
Just ran across this myself and was going to report it.  Yes, the full gesture must be in object with the link for this to occur.  I find this happens most often above images with links such as on the page listed below.  I don't remember this happening before version 3.0.  I'm currently using 3.0.1 on Firefox 77.0.1 on Xubuntu 19.10.

https://apod.nasa.gov/apod/ap200609.html

**Comment by Robbendebiene** [comment] 2020-06-09 21:58
The problem is, that this cannot be prevented (for whatever reason). It worked before because I was blocking the website with the overlay which isn't the case anymore. I'm currently unsure how to solve this.

**Comment by Robbendebiene** [comment] 2020-06-11 10:00
This is fixed in version 3.0.2. It should be available soon.

**Comment by jefferysmall** [comment] 2020-06-11 17:11
You da man!   Thanks very much for so quickly addressing these issues.  Mouse motions are addictive!  Once you start using them, you can never go back!  :-)

**Comment by Robbendebiene** [comment] 2020-06-11 17:30
>  Mouse motions are addictive! Once you start using them, you can never go back! :-)

@jefferysmall I can totally relate to that. :-)

Since it's fixed I'm closing this.

**Closed by Robbendebiene** 2020-06-11 17:30 UTC
Labels: bug

**Comment by larryedwards** [comment] 2022-06-03 20:39
I have a related problem (and am running on the current Gesturefy and Firefox updates).

When autoscrolling (activated by clicking the middle mouse button in a marginal whitespace). In Twitter, when I click the middle button again to end scrolling, if I do so over a link or linked image, Firefox opens the link in a new tab -- interrupting my reading. Most (no?) other websites are not affected, and disabling Gesturefy ends the problem.

Is there a setting to correct this, or is it something you can fix?

**Comment by Robbendebiene** [comment] 2022-06-04 06:55
@larryedwards I've tried to reproduce your problem without any success. To be honest I also cannot think of any way how Gesturefy could cause such a problem.

**Comment by larryedwards** [comment] 2022-06-04 07:02
That's odd, since disabling Gesturefy fixed the problem. Maybe a conflict between it and another extension is cause, since you couldn't reproduce it; or maybe a conflict with one of my Firefox configuration items.

**Comment by Robbendebiene** [comment] 2022-06-04 07:06
If you can reproduce the problem on a clean Firefox profile with only Gesturefy installed please open a new issue.
