### ISSUE TITLE
Gestures stops working on certain pages

### ISSUE THREAD

**Issue by ryanbr** [Robbendebiene/Gesturefy#13] opened 2017-06-17 09:19 UTC
Visit:

`http://www.top10tvboxes.com/s905x-vs-s905-which-is-faster-and-better-android-tv-box/`

On the left hand side, click on 'Best Octa-core TV Boxes' under the "Best-sellers 2017" menu, this will open a new web page.

New web page won't allow gestures to work.

**Comment by Robbendebiene** [comment] 2017-06-17 16:44
Sorry I'm not able to reproduce your bug.
I've clicked the link which opened the following page: http://www.top10tvboxes.com/best-octa-core-tv-boxes-may-2017/ where gestures are working without any problems for me.

**Comment by ryanbr** [comment] 2017-06-18 00:18
https://www.youtube.com/watch?v=fkfT-KeaxV0

Reproducible under Firefox nightly

**Comment by ryanbr** [comment] 2017-06-18 01:50
Came across another one, it seems if the browser launches a popup window/tab, Gesturefy will fail to acknowledge that new tab.

http://www.stuff.co.nz/entertainment/93804932/lizzie-marvelly-devastated-by-anthem-mishap-ahead-of-nz-maori-v-lions-match

Click on the instagram username "lizziemarvelly" launches a new tab, Gesturefy won't work on new instagram tab

**Comment by Robbendebiene** [comment] 2017-06-18 18:57
This is totally a firefox related bug.Every time a new tab/window gets opened from within a page the content script injection fails with the following error:
```
TypeError: context.contentWindow is null[Learn More]  ExtensionContent.jsm:317:9
TypeError: win is null[Learn More]  ExtensionUtils.jsm:143:3
```

Interestlingly it's working if you open the tab manually in a new tab/window.

All you can do is to open in a new bug on https://bugzilla.mozilla.org/

**Comment by ryanbr** [comment] 2017-06-19 01:54
Sure, If you wish to add anything..  https://bugzilla.mozilla.org/show_bug.cgi?id=1374129

**Comment by happysurf** [comment] 2017-06-22 05:30
In my case the "Scroll to the top" and "Scroll to the bottom" doesn't work on my Gmail page, other gestures works fine. 
For now tested only on  + Gesturefy 1.03Firefox 52.5.0 ESR.

**Comment by Robbendebiene** [comment] 2017-06-22 07:52
@happysurf is your gmail page looking like this: https://www.wired.com/wp-content/uploads/2012/10/gmailcompose.jpg? In other words does the scrollbar take the full space at the right side? If not then this isn't a bug, because currently scroll to top/bottom only works for the main scrollbar. I would like to enhance that, but I haven't found a good method yet.

**Comment by happysurf** [comment] 2017-06-22 08:07
My Gmail page is the same of your example image with the scrollbar to the right.
See my image here:
https://upload.cc/i3/JKjwAC.png

**Comment by Robbendebiene** [comment] 2017-06-22 08:15
Yep but the scrollbar is not taking the full height. There also exist some rarely cases where it does take the full height but still wont work.
I'll look again for a possible solution, but I'm not very optimistic.

**Comment by happysurf** [comment] 2017-06-22 08:28
Sorry but I don't understand what do you mean with the "full height".

**Comment by Robbendebiene** [comment] 2017-06-22 08:34
I'm talking about the height of the browsers window where your webpage gets displayed. In your case there is a little white bar (containing the settings icon) at the top which "prevents" the scrollbar to be as high as the window.

**Comment by happysurf** [comment] 2017-06-22 08:42
OK I understand now, but Gmail layout is in the same for all I think.
Thanks for the explanation.

**Comment by Robbendebiene** [comment] 2017-06-22 08:46
>  but Gmail layout is in the same for all I think.

Yes, I was just wanted to point out that this does not apply to every web page :)

**Comment by happysurf** [comment] 2017-06-22 09:12
Same problem in **Yahoo Mail** with similar layout.
If is not an API limitation, you will definitely find a solution.
This is your next challenge. :)

**Comment by mathew832** [comment] 2017-08-11 18:02
I've noticed it not working also but just with pages that use frames. I know, very few sites still use frames but considering my crappy internet lately, I've been checking the stats on my modem page a lot and I forget gesturefy doesn't work with framed sites, at least not those that are all frames.

**Comment by Robbendebiene** [comment] 2017-08-11 19:14
@mathew832 I know how annoying this is and would love to fix this, but its the same problem as for pure svg pages, they both miss the root body element and also don't support drawing. As far as I know there is nothing I can do with the current API, sorry.

**Comment by mathew832** [comment] 2017-08-11 19:32
Ah, makes sense and completely understandable on Mozilla's part but maybe they'll revise the API. Seems they're starting it all off with simple, safe and functional APIs for the time being.

**Comment by stmr** [comment] 2017-08-15 16:08
Can you apply it to the tags they don't work over? I don't know the api. But if you can apply it to different elements, force hacking iframe and other elements might be a dirty solution.

**Comment by ryanbr** [comment] 2017-09-03 04:12
`http://www1.wetter3.de/`  Cant get Gesturefy to work on this page, is it me or the extension?

**Comment by Robbendebiene** [comment] 2017-09-03 07:36
Because this website is using the old html frameset/frames and for a long time I thought I'm not able to fix this, I think I figured a way out :)

**Comment by ryanbr** [comment] 2017-09-11 09:19
Any updates on this? I decided to try on our internal websites which use iframes and Gesturefy didn't work :/ Guessing this would affect a few sites

**Comment by Robbendebiene** [comment] 2017-09-11 11:52
I submitted the new version to Mozilla yesterday, until 1.1.7 gestures should work on pages with framesets without any problems. But iframes should already work in the previous version.

**Comment by happysurf** [comment] 2017-09-11 15:29
New version works on Gmail or Yahoo Mail?

**Comment by Robbendebiene** [comment] 2017-09-11 16:08
> Is still impossible make a gesture for get the focus in location bar?

Sadly no. Currently there is no API to focus the location bar, but mozilla is looking into it. However I would not expect this to happen soon.

Thanks for testing the release! I'm still a little bit nervous that I might have broken some of the functionality, because I did a lot of internal code changes.

**Comment by Robbendebiene** [comment] 2017-09-11 22:00
Since every problem that applies to this issue is solved, I'm closing this.
Please open a new one if you find any further problems.

**Closed by Robbendebiene** 2017-09-11 22:00 UTC
Labels: enhancement
