### ISSUE TITLE
Feature request - multiple links to background tabs

### ISSUE THREAD

**Issue by Shift-3** [Robbendebiene/Gesturefy#165] opened 2017-11-21 15:50 UTC
It would be very useful if there were an option like the current "Link To Background Tab", but which opened all links that the gesture crossed.

I often work with pages that have big lists of links, and need to open several of them in separate tabs. It saves a lot of time to be able to open many of them at once.
,
Apologies if this functionality is already present and I missed it.

**Comment by Robbendebiene** [comment] 2017-11-21 18:47
I guess you mean #47

**Comment by Shift-3** [comment] 2017-11-21 18:52
Yes, thanks. I didn't recognize it from the subject. I knew the function from All-In-One Gestures, where it did not require a key to be pressed.

**Comment by Robbendebiene** [comment] 2017-11-21 19:21
Okay, so you would have to use this gesture multiple times if you have multiple columns of links, right?

**Comment by Shift-3** [comment] 2017-11-21 19:33
Yes...though I guess if I had changed it to something like ULDLU then I could have zigzagged over to another column and gone across those too. Opening one column in a single stroke is all I really use.

**Comment by HillsCloud** [comment] 2017-12-03 00:03
Yes, this feature is incredibly important. I wish the developer would implement this. 

All in one gestures or Mouse gestures would simply open a link by drawing a circle or oval. As long as you complete the circle/oval, it will open all those links that you passed over while drawing that circle/oval. Very easy, convenient and intuitive.

**Comment by Robbendebiene** [comment] 2017-12-06 09:08
This feature is tracked here #47 and even if it's not perfectly the same I'm closing this as a duplicate of #153

**Closed by Robbendebiene** 2017-12-06 09:08 UTC
Labels: duplicate
