### ISSUE TITLE
popup does not work in ubuntu18.04

### ISSUE THREAD

**Issue by zhengruifeng** [Robbendebiene/Gesturefy#539] opened 2020-09-09 02:17 UTC
### Describe your matter in detail
I have been using ubuntu18.04 & firefox & gesturely for more than 1 year, and update them asap.
`[popup] recently closed tabs` and `[popup] all tabs` always show a blank.

### Screenshots or further assistance
![image](https://user-images.githubusercontent.com/7322292/92546550-69556e00-f285-11ea-863a-17efc0934311.png)

### Your System
- Operating system: ubuntu 18.04 (Kernel: 5.4.0-47-generic, GNOME: 3.28.4)
- Firefox version: 80.0.1
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment] 2020-09-09 07:35
Was this caused by any update, or did you change anything else?
It's working for me, so I need more information then just "it's not working". Please open about:debugging#/runtime/this-firefox and click on the "Inspect" button for Gesturefy. Then at the top choose "console" and click the clear button. Now do the popup gesture and head back to the console to see if there are any logs. Please post them here.

**Comment by zhengruifeng** [comment] 2020-09-09 08:07
@Robbendebiene  Thank you for the quick response.

> Was this caused by any update, or did you change anything else?

This issue existed since I switched to ubuntu18.04 about 1 year ago. I updated kernel/gnome/firefox/gesturefy, but it always existed.

actually, I can open the url in the popup list, but the **names of tabs are missing**.
![image](https://user-images.githubusercontent.com/7322292/92571627-edbfe500-f2b5-11ea-9799-38a4cbc11189.png)


> Please open about:debugging#/runtime/this-firefox and click on the "Inspect" button for Gesturefy. Then at the top choose "console" and click the clear button. Now do the popup gesture and head back to the console to see if there are any logs. Please post them here.

![image](https://user-images.githubusercontent.com/7322292/92571948-57d88a00-f2b6-11ea-8fdf-a0a1022f80ca.png)

**Comment by Robbendebiene** [comment] 2020-09-09 08:59
>  I can open the url in the popup list, but the names of tabs are missing.

In this case a permission is probably missing. Please try recreating your popup gestures or reassigning the commands.

**Comment by zhengruifeng** [comment] 2020-09-09 09:06
@Robbendebiene  It is OK after reassigning the commands. Thanks!

**Comment by Robbendebiene** [comment] 2020-09-09 18:10
No problem!

**Closed by Robbendebiene** 2020-09-09 18:10 UTC
