### ISSUE TITLE
Gesturefy functions unproperly when scale is in effect

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#421] opened 2019-09-19 07:00 UTC
### Describe your matter in detail

![_](https://user-images.githubusercontent.com/799021/65220637-c62fa580-dac3-11e9-9af2-70174dd30f58.jpg)

When scale is in effect the lines drawn by right click are skew from mouse pointer to left-top

Some times it works fine, sometimes not, but it often does not work for scaled pages

### Your System
- Operating system: Linux Mint 19.2
- Firefox version: FF v69
- Gesturefy version: 2.1.2

**Comment by Robbendebiene** [comment] 2019-09-19 08:09
Please post a screenshot of the actual problem.

Are you using "Text Zoom"? (you can check that by opening the menubar pressing Alt, then: View -> Zoom -> Only zoom text)

**Comment by KES777** [comment] 2019-09-19 08:59
I will post video when it is appears again

**Comment by Robbendebiene** [comment] 2019-10-25 12:52
Closed as potential duplicate of https://github.com/Robbendebiene/Gesturefy/issues/426

**Closed by Robbendebiene** 2019-10-25 12:52 UTC
Labels: need info, unable to reproduce
