### ISSUE TITLE
Feature Request: Open several links in tabs

### ISSUE THREAD

**Issue by github-bugsubmit** [Robbendebiene/Gesturefy#564] opened 2021-01-27 20:42 UTC
The "open link in new tab" is probably the single most used function in Gesturefy, for me at least. It's so unbelieveably useful.

Once upon a time, another -- now dead -- mouse gesture addon (I forgot its name) supported opening either **the** link (that is, one) in a new tab, or, alternatively, **every** link under the gesture's path. I think it would be very little work to implement this (basically just a loop, and one extra item in the config dialog), but it would be immensely helpful.

On sites that give me many choices (so basically most sites, but notably _every_ shop), I tend to scan the list, and open everything that I might be interested in to a new tab, respectively. This not only reduces time lost to network latency, it is also more practical in terms of not losing track and missing stuff.  Often, there's two or three things that I want to read side by side, and just being able to do one stroke would make it much easier.
Once done, I work off open tabs (often 50 or so...) one after another.

Some sites (notably tool shops) only ever show you 12 items of whatever. So guess what I'm doing, I'm opening pages 1, 2, 3, and 4, to browse the full inventory. Which, unluckily, takes 4 actions when it could be a single stroke.

**Comment by Robbendebiene** [comment] 2021-01-27 23:17
This has already been requested here #298. That's why I'm closing this as a duplicate.

Nevertheless I want to give some feedback to your writings.

> The "open link in new tab" is probably the single most used function in Gesturefy, for me at least. It's so unbelieveably useful.

To be honest, I never understood why people use this command. I'm always using the mouse wheel button for this :)

>  I think it would be very little work to implement this (basically just a loop, and one extra item in the config dialog), but it would be immensely helpful.

This is true for simple websites, but when frames get involved it gets quite complicated. Basically it requires a lot of underlying code changes, because of that it hasn't been added yet.

At the end I'm more in favor with https://github.com/Robbendebiene/Gesturefy/issues/47 because it's not bound to a specific mouse movement, but it suffers from the same problem.

You may want to try Snap Links Plus (https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/) It does the job even though in a slightly different way.

Please continue add any further comments in the other issue. Thanks

**Comment by Robbendebiene** [comment] 2021-01-27 23:17
Duplicate of #298

**Closed by Robbendebiene** 2021-01-27 23:17 UTC

**Comment by nayuki** [comment] 2023-11-17 01:46
> Once upon a time, another -- now dead -- mouse gesture addon (I forgot its name) supported opening either **the** link (that is, one) in a new tab, or, alternatively, **every** link under the gesture's path.

It was [FireGestures](http://www.xuldev.org/firegestures/features.php) and I used it. I miss this particular feature.
