### ISSUE TITLE
Opening a link into a new tab issue

### ISSUE THREAD

**Issue by enfuego360** [Robbendebiene/Gesturefy#155] opened 2017-11-20 23:57 UTC
When I open a link into a new tab, it opens next to the tab that I opened the link from. I have Firefox set up to open new tabs at the end, which is what I want to happen when I open a link into a new tab. Is this a glitch or is there a setting in Gesturefy that I am missing?

**Comment by Robbendebiene** [comment] 2017-12-04 22:25
This is not a glitch. Addons do not have access to these kind of properties so I'll have to implement an extra setting for this by my own. I'll use the other issue to track this, therefore I'm closing this one.

**Comment by Robbendebiene** [comment] 2017-12-04 22:25
Duplicate of #196

**Closed by Robbendebiene** 2017-12-04 22:25 UTC
