### ISSUE TITLE
trigger:right-click / Wheel up / action:scroll to the top 

### ISSUE THREAD

**Issue by fantaboy** [Robbendebiene/Gesturefy#87] opened 2017-11-15 03:33 UTC
trigger:right-click / Wheel up / action:scroll to the top 

Action doing well ,but ,,,

Right-click pop-up menu is showing up...

**Comment by rippeddisc** [comment] 2017-11-15 07:48
agreed.  unable to use gestures or even record a new one as right-click popup menu is in way

**Comment by Robbendebiene** [comment] 2017-11-15 09:20
In case you are using Linux or Mac, please read the addon description or this issue: https://github.com/Robbendebiene/Gesturefy/issues/1#issuecomment-344508428 However you can use gestures if you switch to the middle or left mouse button.

**Comment by rippeddisc** [comment] 2017-11-15 11:11
thanks rob...switched to left-click to activate however i am unable to highlight/copy text now.  had to deactivate :/

**Comment by Robbendebiene** [comment] 2017-11-15 12:52
Thats why I'm using the middle mouse button on my linux system. You also can make use of the Gesture-Supression-Key. If you hold it, you should be able to select text as usual.

**Comment by rippeddisc** [comment] 2017-11-15 18:24
i tried using suppression but it did not let me highlight text as expected.  on osx/magic mouse

**Comment by Robbendebiene** [comment] 2017-11-21 22:43
@rippeddisc You have to use shift or alt key, because firefox is behaving differently on ctrl + mouse.
Duplicate of #1

**Closed by Robbendebiene** 2017-11-21 22:43 UTC

**Comment by rippeddisc** [comment] 2017-11-22 10:39
using the shift key with no success



www.ExpandingVisualReality.com <http://www.expandingvisualreality.com/>

FACEBOOK <http://www.facebook.com/afeinphoto>
TWITTER <http://www.twitter.com/afeinphoto>
INSTA <https://instagram.com/afeinberg_photography/>

“...this is the best part of the trip....”

rippeddisc@gmail.com
808.634.5804
