### ISSUE TITLE
Bookmark for site gets deleted when gesturing on the site

### ISSUE THREAD

**Issue by mathew832** [Robbendebiene/Gesturefy#16] opened 2017-08-08 14:50 UTC
Specifically with my modem page I've had this issue. Gestures don't work but any up/down/left/right right-click gesture and then moving my mouse from the Firefox window or to the tabs window will automatically make my bookmark disappear. I don't know if this is a bug in FF or your extension. I'm assuming FF since it seems to have a permission beyond what the extension or the API you're using should be capable of or requested with their new webextension model.  

This doesn't happen with the extension disabled. It doesn't happen on my router's page (192.168.1.1), only my modem's (192.168.100.1) which I guess rules out Mozilla not allowing the API to access local network pages. I can click anywhere on the modem page, regardless of what he element is below it and it happens. But even hovering over the context menu after gesturing will trigger the deletion of the bookmark. 

I recorded it, not sure why but [here you go](https://gfycat.com/gifs/detail/conscioussimplegoldenretriever).

Edit: Forgot, I'm on Nightly v57.0a1.

Also, another unrelated thing, when using the Stylus extension and [this userstyle](https://userstyles.org/styles/42313/dark-wikipedia), when right-clicking and moving on wikipedia, the whole page is grayed or blackened if I change it to black by editing the stylesheet. Not a big deal and can't think of any use cases off-hand where it'd be a problem. But if you're wanting to keep your extension more user friendly, probably best to make sure it doesn't mess with the user's page display.

**Comment by Robbendebiene** [comment] 2017-08-08 21:03
This seems strange..
Currently I'm not able not reproduce the bug on firefox 54.
1. I'll need some more information to figure this out since I can't open your modems webpage, can you search in the webpages sourcecode (rightclick > show sourcecode) for something like "frame" or "frameset". At least these are the only html elements I can think of that could make problems, because they are too old and only barely supported.
2. Can you also tell me which gesture does trigger bookmarking for you (if you have one)?
3. Just to clarify things for me, this does NOT happen on websites where the addon is working properly?
4. Does this happen every time, or only when you first right click and then move your mouse up to the top?
5. Maybe you can test if the problem persists in the current stable firefox release?

To address the other problem:
Can you please send me an example screenshot of this? Even though I think that I'm unable to "fix" this, because Stylus is messing with my extension:

```
    background-color: transparent !important;
    color: #bcbcbc !important;
```
(the `!important` is overwriting my colors)
But I think I'm also going to add `!important` to all my elements which could fix the problem, but it depends on how and when Stylus is adding the css styles.

**Comment by mathew832** [comment] 2017-08-09 04:43
1. Yes, the source does indeed include those. [Pastebin of source](https://pastebin.com/6vpPLtD6).

2. In case it's not clear, the gestures don't create a bookmark, only delete it. But it seems like right-clicking and moving my mouse in any direction to any degree at all and then moving the mouse to focus off the page, it'll instantly delete it. 

3. Works fine everywhere else, thanks for your work. Except about and Mozilla pages, which I know is Mozilla's fault but understandable. 

4. Every time.

5. I'll test on my 54 install and edit this line. 

6. Copy/paste: 
*{
   background-color: transparent !important;
   color: #bcbcbc !important;
}

body, div, form, table, tbody, tr, td, fieldset, ul, li, a,
#content, #bodyContent{
   background-color: #000 !important; /*personal edit*/
   background-image: none !important;
}

I deleted the "div" part and that solved it, but of course, doesn't make wiki look good.

**Comment by uegajde** [comment] 2017-08-09 10:07
I have same problem.
It seem to happen in any website. (tested in github, google, facebook .... and so on)
Specifically for the the right click which has very slight movement will trigger gesturefy instead of context menu. And this will **trigger an action which is not assigned to any gesture**.

In my case, the triggered action is 'Toggle Bookmark', too. 
After I assign some gesture for 'Toggle Bookmark', it becomes to trigger 'New tab right', which is also not assigned to any gesture.
Same, after 'New tab right' is 'New tab left'

**Comment by mathew832** [comment] 2017-08-09 12:42
All this time, I didn't realize gesturefy had an option to toggle bookmarks. I guess that would've saved me some diagnostic time. Playing with that a bit, I assigned an L shape for toggling bookmarks. It doesn't seem to work but on my modem's page, it copies the tab but only when I focus off the web page. Yeah, somethings a bit wonky with the code.

**Comment by Robbendebiene** [comment] 2017-08-09 13:04
Alright, thanks to both of you for the report! I'm looking into it.

**Comment by mathew832** [comment] 2017-08-09 14:41
I don't normally bother with bug reports but this addon is well done, something I'd use often and has great potential. Thanks for the quick fix.

**Comment by Robbendebiene** [comment] 2017-08-10 14:22
Thank you :)
I submitted the new version, hopefully it will get approved .

**Closed by Robbendebiene** 2017-08-10 14:22 UTC
Labels: bug
