### ISSUE TITLE
Right click draw over any link, open all link in new tab

### ISSUE THREAD

**Issue by paul3333** [Robbendebiene/Gesturefy#153] opened 2017-11-20 22:00 UTC
Hello, thanks for this very good addon
i wish get back the useful function in FireGestures
when i hold the Ctrl key and draw over any link, it will open all links to new tab
if hold the Shift key will copy all the links
![firegestures](https://user-images.githubusercontent.com/17485651/33043677-36b926ce-ce81-11e7-805c-b705080f3743.jpg)

![test mp4_20171121_055521 708](https://user-images.githubusercontent.com/17485651/33043687-41d10ec8-ce81-11e7-910b-b73d515b8e4f.jpg)

sorry my english not very well

**Comment by Robbendebiene** [comment] 2017-11-20 22:43
I guess you are talking about this: #47

**Comment by Robbendebiene** [comment] 2017-11-21 07:33
Duplicate of #47

**Closed by Robbendebiene** 2017-11-21 07:33 UTC
