### ISSUE TITLE
Open link in new tab not working on some links

### ISSUE THREAD

**Issue by heizie78** [Robbendebiene/Gesturefy#130] opened 2017-11-18 17:32 UTC
The gesture to open a link in a new (background) tab is not working on all links. e.g. on some Tumblr posts having multiple pictures, the gesture is not working when executed on the link to one of those pictures.

**Comment by Robbendebiene** [comment] 2017-11-18 17:41
Can you please send me an example? This may be already fixed in the next update (https://github.com/Robbendebiene/Gesturefy/issues/90)

**Comment by heizie78** [comment] 2017-11-18 18:57
Maybe the same issue. Try to open picture 2 and 3 on that blog with the gesture. http://architectureblog.tumblr.com/
With right-click --> open in new tab it works fine.

**Comment by Robbendebiene** [comment] 2017-11-18 19:13
Sorry, everything is working fine for me.

**Comment by heizie78** [comment] 2017-11-19 10:38
Please see screenshot. My gesture to open link in background is just UP. What it is actually doing is RIGHT-UP or LEFT-UP when I execute the gesture on the image link. It looks like it is starting the gesture on the wrong position. For other links it is working fine. I'm on Win10 with FFv57 and I just completely reset my FF profile.
![gesture](https://user-images.githubusercontent.com/32620611/32989821-f7b25b62-cd1d-11e7-96a3-0a272ac0c525.jpg)

**Comment by Robbendebiene** [comment] 2017-11-19 17:40
Strange. Which version of gesturefy are you using? Also which mouse button do you use to draw your gestures? Does it happen all the time when you start a gesture on that link/image?

**Comment by heizie78** [comment] 2017-11-19 17:58
I'm using version 1.1.15. As button I use the right-mouse button. Yes, it happens all the time.
I was wondering if it may have to do with the fact that I'm using two high-res screens?! I have noticed that when I place the FF window on the left screen the situation above occurs. When I place FF on the right screen the exact opposite gesture error occurs. It is doing gesture RIGHT-UP all the time. Also the green gesture trail is coming from the other side. I switched off one screen, but still happens. Maybe it has only to do with high-res?

**Comment by heizie78** [comment] 2017-11-19 17:59
Just switched to resolution 1366x768 and it is working fine!

**Comment by heizie78** [comment] 2017-11-23 20:24
Noticed the same issue with forward/backward (right/left) gestures on some sites. e.g. here http://www.swissquote.ch/index/index_quote_e.html
seems to be an issue with the screen resolution and/or window size.

**Comment by Robbendebiene** [comment] 2017-11-23 20:58
It's not related to the gesture you use.

> seems to be an issue with the screen resolution and/or window size.

What window size leads to this problem? Because I'm still unable to reproduce it.

**Comment by haugs** [comment] 2017-11-24 10:34
I have the problem on 1920x1080. It occurs on my laptop screen, but also when when using an extrenal monitor.
What I can confirm is that the behaviour worsenes when extending the screen to a secondary monitoring.
When I run FF on my primary screen the gestures are working fine in the top left corner and its getting worse when using it further to the right or bottom. When I run FF on the secondary screen the problem is already strongly present in the top left corner.

**Comment by heizie78** [comment] 2017-11-24 15:51
I can confirm that. I'm using two high-res screens with 3200x1800 and 3840x2160. Only dramatically reducing the resolution on both screens or using only one screen with low-res like 1366x768 fixes the issue.

**Comment by Robbendebiene** [comment] 2017-11-24 22:39
Can you please open the console (F11), execute the following line of code: `window.devicePixelRatio` and tell me the output number.
Also ensure that the website where you run this code is not zoomed in or out.

**Comment by heizie78** [comment] 2017-11-26 20:27
The output is 2

**Comment by Robbendebiene** [comment] 2017-11-27 00:16
@heizie78 Can you please try if it is fixed in [this version](https://github.com/Robbendebiene/Gesturefy/archive/master.zip).
1. donwload and unzip
2. disable the existing gesturefy addon
3. go to about:debugging and select "load temporary addon"
4. select the manifest.json from the unzipped zip

**Comment by heizie78** [comment] 2017-11-27 08:21
Looks fixed! :-) At least until now I did not experience any issues.

**Comment by Robbendebiene** [comment] 2017-11-27 10:19
I will try to upload the patch this week.

**Comment by Robbendebiene** [comment] 2017-11-28 19:42
Version 1.1.17 is available on Mozilla.
Bug fix reference: https://github.com/Robbendebiene/Gesturefy/commit/331bdaff9a374f2b014fb0cb0fbbaa5e7c038c56

**Closed by Robbendebiene** 2017-11-28 19:42 UTC
