### ISSUE TITLE
about:newtab does not work as home page 

### ISSUE THREAD

**Issue by niedworok** [Robbendebiene/Gesturefy#66] opened 2017-10-11 16:30 UTC
Configuring about:newtab as the home page for the open home gesture does not work.

The gesture is being recognized (the text hint appears), firefox however stays on the page the gesture was executed.

Firefox is 57.0b7 x64 on Windows 10

Regards

**Comment by Robbendebiene** [comment] 2017-10-11 18:19
The problem is that about:newtab is considered as a privileged url, wherefore I cant open it until the bug I mentioned here is "fixed".

**Comment by niedworok** [comment] 2017-10-12 14:17
Understood. I guess we'll have to wait and see. Thank you for Gesturefy!

**Comment by niedworok** [comment] 2017-10-12 14:17
Closed issue by accident, I'll reopen it as a reminder. Hope you don't mind...

**Comment by Robbendebiene** [comment] 2017-10-12 15:19
No problem :) I'll label it as "api limitation" in the meantime.

**Comment by kkot** [comment] 2017-10-16 18:47
@niedworok I work around this issue by setting www.google.com as new tab page and using https://addons.mozilla.org/pl/firefox/addon/new-tab-override/
Before I used blank page so it works for me.

**Comment by niedworok** [comment] 2017-10-18 14:09
Thanks for the heads up, this works. 

(Rather off topic, what i actually would like, is a configurable new tab page like this:

https://addons.mozilla.org/en-US/firefox/addon/speed-start/

I guess I'll have to write one myself, if nobody else comes up with an addon :-) )

**Comment by Robbendebiene** [comment] 2017-10-18 14:11
@niedworok Use https://addons.mozilla.org/de/firefox/addon/new-tab-override/ :)

**Comment by Robbendebiene** [comment] 2017-10-18 14:14
@niedworok Maybe you can use something like https://lifehacker.com/5923751/two-excellent-customizable-start-pages-worth-trying-now-that-igoogles-going-away in combination with "new-tab-override" what kkot suggested?

**Comment by niedworok** [comment] 2017-10-18 19:21
I will try that. Thank you all for the suggestions!

**Comment by Robbendebiene** [comment] 2018-11-19 21:14
I'm closing this, since this won't to be possible in the near future.

**Closed by Robbendebiene** 2018-11-19 21:14 UTC
Labels: api limitation
