### ISSUE TITLE
Gesturefy stopped working and settings page is blank after upgrade to Firefox 80.0.1

### ISSUE THREAD

**Issue by Monk57** [Robbendebiene/Gesturefy#538] opened 2020-09-06 12:50 UTC
Guesturefy stopped working after upgrading to Firefox 80.0.1.  Settings page is blank.  Have tried disabling and restarting ... no effect.  Have uninstalled and reinstalled ... still not working.  Restarted browser after each attempt.  Not working.

Windows 7 pro
Firefox 80.0.1
Gesturefy 3.06 (latest version)
![Gesturefy](https://user-images.githubusercontent.com/70846592/92326144-f0a0a880-f01d-11ea-87a8-bbadf050c5af.jpg)

**Comment by Robbendebiene** [comment] 2020-09-06 16:33
This looks very weird. Can you reach the about section (the symbol with the i) to reset Gesturefy?
If not please open the console on the settings page via ctrl + shift + K, reload the page and post any output here.

**Comment by Monk57** [comment] 2020-09-06 22:42
Attached are the images of what I get when I click on the (i) symbol and what I get after doing  ctrl + shift + K on the settings page.  Everything worked until I updated Firefox this morning.  I have also close and restarted the browser a couple of times.
![Gesturefy (i) click](https://user-images.githubusercontent.com/70846592/92336534-d42d5c00-f06f-11ea-9919-eaf61b13ab32.jpg)
![Gesturefy 2](https://user-images.githubusercontent.com/70846592/92336620-777e7100-f070-11ea-9481-1cb69678bcb7.jpg)

**Comment by Robbendebiene** [comment] 2020-09-07 07:45
Honestly this sounds like a Firefox error to me. At least the error logs are not directly caused by Gesturefy.
Maybe you can try installing Gesturefy on a new clean profile. If it doesn't help you can still switch back to your old one.

**Comment by Monk57** [comment] 2020-09-08 00:38
I tend to agree with you.  I tried another gesture add on and it did not work either.  I guess we shall see what happens on the next update.  Thank you for the help.

**Comment by XGTIGER** [comment] 2020-09-08 03:25
The same situation with me. About 2 months ago, it became not working for me.Today ,I opened the setting,blank page found! The FF version is 80.0.1,too.

**Comment by Robbendebiene** [comment] 2020-09-08 08:12
> I tried another gesture add on and it did not work either. 

In this case I'd suggest one of you opens a ticket here: https://bugzilla.mozilla.org
It probably would be interesting to know which add-ons work and which not, in order to work out the root of the problem.

**Comment by kramola-RU** [comment] 2020-09-08 16:32
> Maybe you can try installing Gesturefy on a new clean profile.

**FF 80/01 x32 clean profile**  +  **Gesturefy 3.06**  =  **no problem**

**Comment by Monk57** [comment] 2020-09-08 16:44
That does not solve the problem.  It is also nice to see that I am not the
only one with the issue.

**Comment by Robbendebiene** [comment] 2020-09-18 13:32
Since the reason for the data corruption is pretty much unknown and probably caused by a Firefox update I'm closing this.

**Closed by Robbendebiene** 2020-09-18 13:32 UTC
Labels: external
