### ISSUE TITLE
Feature request: Ctrl + Right Mouse Pressing over a link to make an action on it

### ISSUE THREAD

**Issue by helperman** [Robbendebiene/Gesturefy#366] opened 2018-11-08 22:11 UTC
Thanks for excellent extension!

Can you add feature to open URL-s after Ctlr + Right Mouse Pressing over it?
You can watch the idea here on youtube:
https://youtu.be/DrETMnki7PU?t=77

Start watching video at 1:17 

It had worked in old version of FireGestures.
It worked without selecting the text by mouse.
It also worked even if start point is not a link but a gesture goes through a link (or many links).
It was also able to handle multiple links during one gesture.
User might change hotkey (use it with Ctrl, Alt or Shift) and set up different action (open in new tab in background, open in new tab and focus on it, or copy URL of that tab/tabs) for these three keys separately in addons options.

**Comment by Robbendebiene** [comment] 2018-11-10 09:01
Hey, maybe I'm misunderstanding you, but it sounds like you are describing [Keypress Gestures](https://github.com/Robbendebiene/Gesturefy/issues/47)?

**Comment by Robbendebiene** [comment] 2018-11-10 15:01
Alright, in this case I'm closing this issue as a duplicate.

**Comment by Robbendebiene** [comment] 2018-11-10 15:01
Duplicate of #47

**Closed by Robbendebiene** 2018-11-10 15:01 UTC
Labels: duplicate
