### ISSUE TITLE
Focus Left/Right tab no longer wraps around

### ISSUE THREAD

**Issue by rodalpho** [Robbendebiene/Gesturefy#487] opened 2020-06-07 21:08 UTC
In previous versions, focus left/right tab wrapped around, so if you were on the rightmost tab and focused to the right of that, it would switch to the leftmost tab. Can we restore this behavior?

**Comment by Itchiii** [comment] 2020-06-08 07:05
Take a look here #471, everything is described there. You just have to turn on the cycling again.

**Comment by Itchiii** [comment] 2020-06-08 14:55
Duplicate of #471

**Closed by Itchiii** 2020-06-08 14:55 UTC

**Comment by rodalpho** [comment] 2020-06-08 18:02
Thank you, recreating the gestures did indeed fix it. Didn't see any way to set tab cycling otherwise.
