### ISSUE TITLE
gestures often not recognized

### ISSUE THREAD

**Issue by RobbieGNL** [Robbendebiene/Gesturefy#503] opened 2020-06-16 16:54 UTC
Since the lastest update, gestures are often not recognized anymore. I guess it has something to do with the new feature that allows for diagonal movements. Going to delete this addon now. Hopefully it will be fixed so I can use it again later.

**Comment by Robbendebiene** [comment] 2020-06-16 17:16
Duplicate of #500

**Closed by Robbendebiene** 2020-06-16 17:16 UTC
