### ISSUE TITLE
Toggle bookmark

### ISSUE THREAD

**Issue by kabbill** [Robbendebiene/Gesturefy#493] opened 2020-06-10 10:11 UTC
Hi, I tried the toggle bookmark action in v3 and it does not show bookmarks.
In fact, it adds the page to bookmarks. So it should be renamed "Add to Bookmark".

It would be great though if there was an action that hides/shows bookmarks in the left side.

**Comment by Robbendebiene** [comment] 2020-06-10 10:21
Hi, please open the browser console (ctrl + shift + J), clear it (by clicking the trash symbol) and ensure that the settings are checked as in the screenshot below.

![grafik](https://user-images.githubusercontent.com/13716661/84256803-b6099b80-ab14-11ea-9b10-f2b91f3fad48.png)

After that switch to a tab and try the bookmark gesture. Then return to the console and post any error logs here.

**Comment by Robbendebiene** [comment] 2020-06-10 10:23
- Hi, I tried the toggle bookmark action in v3 and it does not show bookmarks.
- In fact, it adds the page to bookmarks. So it should be renamed "Add to Bookmark".
- 
- It would be great though if there was an action that hides/shows bookmarks in the left side.

This gesture adds the current site as a bookmark and if you do the gesture again it will remove it from bookmarks. That's why it's called "toggle".

**Comment by Robbendebiene** [comment] 2020-06-10 10:32
Duplicate of #141

**Closed by Robbendebiene** 2020-06-10 10:32 UTC
Labels: duplicate
