### ISSUE TITLE
"[Popup] All tabs" + mouse wheel to switch to the tab

### ISSUE THREAD

**Issue by Dituar** [Robbendebiene/Gesturefy#647] opened 2022-08-19 21:48 UTC
Hi again)
I think it's possible to improve the speed/usability of interaction by combining the mouse wheel gesture and "[Popup] All tabs" to customizable "Last open N tabs" https://github.com/Robbendebiene/Gesturefy/issues/301 to not make a gesture , and do not click the mouse.
What I mean: while on the page, press the right mouse button, roll the mouse wheel, opens "[Popup] All tabs" with displayed tabs last accessed ascending, without releasing the right mouse button, roll the wheel to select the tab, release the right mouse button to switch to the selected tab.
I hope I explained clearly)

- Operating system: win 7 64
- Firefox version: 103.0.2 (64 bit)
- Gesturefy version: 3.2.5

**Comment by Dituar** [comment] 2022-08-20 13:16
Or another quick way to switch to the last N tab. Maybe this way is better/easier to implement. 
Draw gesture with a right-click the number "2" to switch to the pre-previous tab (there is a separate gesture for switching to the previous tab), draw number "3" to switch to the pre-pre-previous tab, and so on...

I want to switch between the last tabs faster, more faster))
Maybe someone can think of a better way?

**Comment by Robbendebiene** [comment] 2022-08-20 19:30
Hi, correct me if I'm wrong, but I think this is a duplicate of the following issue: https://github.com/Robbendebiene/Gesturefy/issues/245 (it becomes more clear at the end of the issue). Maybe I should rename the title.

**Comment by Dituar** [comment] 2022-08-21 10:13
Yes, as far as I understood, this is what I described, but with one condition: in that issue it is proposed to move the list with a roller while the selection field is stationary. And I propose to move the selection field with the roller when the list is stationary, only when the list is large and the selection field reaches the end of the visible list does it start moving the list.
Although he may have meant it, he just didn’t describe it clearly)

But as far as I understand, you do not like this implementation) Yes, I also thought about it, that it complicates the usability a little, so immediately after creating this issue I created issue #648. You can delete this issue #647 if you think it's a duplicate.
I'm just looking for a way to switch between recent tabs faster.

**Comment by Robbendebiene** [comment] 2022-08-21 20:29
I see, even though the last comment of the issue doesn't describe the "select by scrolling" feature I think this is what everyone is really interested in. Therefore I'm closing this as a duplicate. Any further ideas are welcome in that issue.

Just some closing words on this: I totally agree that this functionality would be cool and useful. But it's neither easy to integrate nor is it really compatible with normal mouse gestures as you already mentioned. I consider wheel and rocker gestures just as a nice little extra functionality of Gesturefy and not as something fully integrated. That's part of why I'm not convinced to change the popup working principle yet.
Thanks for your understanding.

**Comment by Robbendebiene** [comment] 2022-08-21 20:29
Duplicate of #245

**Closed by Robbendebiene** 2022-08-21 20:29 UTC
