### ISSUE TITLE
Rocker gesture hardly works

### ISSUE THREAD

**Issue by thany** [Robbendebiene/Gesturefy#49] opened 2017-09-28 19:37 UTC
Rocker gestures need some love.

They oftenly just simply don't work. Like, at all. Sometimes when they do, they'll still display the context menu. I just have to try the backwards-gesture three or four times before it works.

**Comment by Robbendebiene** [comment] 2017-09-28 21:57
Which Firefox version are you using and what is your operating system?

**Comment by thany** [comment] 2017-09-29 09:49
Firefox 56 on Windows 10, both x64

**Comment by Robbendebiene** [comment] 2017-09-29 10:51
Hm it's working fine for me, maybe you are pressing the mouse buttons too fast so they are not in the right order?

**Comment by janeisenmenger** [comment] 2017-09-29 18:31
I'm having trouble on 57.0b3 as well - Rocker gestures dont work at all. Rest of gestures seems to still work fine after updating.

**Comment by rodalpho** [comment] 2017-09-30 00:53
For me, unless I very do the rocker gestures very deliberately, it seems like the addon picks whether to do a RL or LR rocker at random. 

I have R+L set to "close current tab" and L+R set to "restore closed tab". So it's very disorienting when it messes up. 

In its current state, rocker gestures are essentially not usable for me.

**Comment by will76** [comment] 2017-09-30 14:45
+1 Does not work all the times. Weird.

Using the FF 57 beta

**Comment by Robbendebiene** [comment] 2017-09-30 21:32
@will76 What actions exactly does it "throw"? and what are your selected actions?

@all I'll need more information how to reproduce it, because it's working just fine for me. Maybe it only happens on certain pages, after a specific amount of clicks, or if a specific action is selected.

**Comment by stmr** [comment] 2017-10-05 17:55
For me they work flawlessly. The only thing is that they only work after the page has been loaded, bud that's sadly how WebExtensions work.

**Comment by thany** [comment] 2017-10-10 09:31
Perhaps they only work best on ajaxified (I hate that word :)) websites, where each link is not loaded by the browser, but through ajax. Youtube and Github are good examples of this.

Another thing I noticed is the back-gesture oftenly displays the context menu at the end, esp when the gesture ends while the previous page is already about to render.

**Comment by SilentSin** [comment] 2017-10-10 10:20
The issue isn't that it picks a direction randomly, it's that it picks the direction based on the side you release first rather than the side you press first.

In Fire Gestures: RMB + LMB = Rocker Left on button down.

In Gesturefy: RMB + LMB = nothing on button down, then go in whichever direction you release first.

I greatly preferred the Fire Gestures way.

**Comment by rodalpho** [comment] 2017-10-10 12:42
That isn't actually the problem for me, I just tested it out and when I do a R+L chord I definitely release the left before the right. It's just that if I don't do it slowly and deliberately, it executes the L+R assigned function. And this is actually repeatable.  Do it fast, fails. Do it slow, works.

**Comment by Robbendebiene** [comment] 2017-10-10 13:40
> Another thing I noticed is the back-gesture oftenly displays the context menu at the end, esp when the gesture ends while the previous page is already about to render.

Yep, in this state (page loading) it's impossible to do anything including contextmenu suppression.

>The issue isn't that it picks a direction randomly, it's that it picks the direction based on the side you release first rather than the side you press first.
> In Fire Gestures: RMB + LMB = Rocker Left on button down.
> In Gesturefy: RMB + LMB = nothing on button down, then go in whichever direction you release first.
> I greatly preferred the Fire Gestures way.

I preferred it too, but I remember some problems with supressing the context menu when using mosuedown. However I'm currently not able to reproduce them.

**So here is a version with mousedown which (in theory) should fix most of the problems. Maybe someone can help testing it, because I first implemented it this way and changed it to mouseup due to some problems:**
1. disable you current version of gesturefy in the browser
2. download and unzip: https://github.com/Robbendebiene/Gesturefy/archive/rockerOnMouseDown.zip
3. go to "about:debugging" in firefox and click "load addon temporary"
4. choose the manifest.json file in the "src" folder
5. please test different actions like: next tab, reload, history back etc.

> That isn't actually the problem for me, I just tested it out and when I do a R+L chord I definitely release the left before the right. It's just that if I don't do it slowly and deliberately, it executes the L+R assigned function. And this is actually repeatable. Do it fast, fails. Do it slow, works.

I'm pretty sure thats the same "issue", because it's intuitv to release the first pressed button when doing it fast. You should consider using this gesture more by holding one button down and then clicking the other mouse button multiple times (instead of "rocking" multiple times). Thats the actual strength.

**Comment by stmr** [comment] 2017-10-10 13:51
@SilentSin I can confirm this, and it doesn't matter what the speed is @rodalpho it's just the way it's implemented (onMouseUp)

@thany not 100% sure when do webextensions get activated, but I'm pretty sure that some "ajaxified" pages can draw a basic page layout and process the rest through ajax, so the webextension gets to work a bit faster than on pages that have to draw everything at once so that might be the reason. Should work the same way on all pages if they were loaded when you started to perform the gestures.

@Robbendebiene Thanks! Tried it for a while and haven't come upon any problem and it also feels faster :) (but I've tried only next/previous tab, history back/forward and few reload actions)

**Comment by rodalpho** [comment] 2017-10-11 01:00
If the new version fixes it, maybe you're right and the mousedown event is what matters. 

I use R+L to close the current tab, so the use case of closing multiple tabs in sequence in the same order is infrequent. But it does happen and I do use it that way too.

**Comment by Robbendebiene** [comment] 2017-10-15 13:06
I'm closing this issue since rocker gestures are now triggered on mouseup. If you have any further problems let me know.

**Closed by Robbendebiene** 2017-10-15 13:06 UTC

**Comment by rodalpho** [comment] 2017-10-15 19:01
I can confirm this 100% fixed the problem for me. Thanks again!

**Comment by martin-wanderer** [comment] 2018-01-01 21:52
RMB still opens context menu. Som RMB+LMB doesn't work, while LMB+RMB works pretty well.
Gesturefy 1.1.17, Firefox 57.0.3, Ubuntu 17.10

**Comment by Robbendebiene** [comment] 2018-01-01 23:08
@martin-wanderer Please read the [addon description](https://addons.mozilla.org/firefox/addon/gesturefy), or the [project description]( https://github.com/Robbendebiene/Gesturefy), or [here](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md).

**Comment by martin-wanderer** [comment] 2018-01-02 00:04
Yes, I've already read that. 
Does this
> MacOS & Linux users can only use the right mouse button using the latest Firefox 58!

concern rocker gestures as well as normal ones?

**Comment by Robbendebiene** [comment] 2018-01-02 09:08
@martin-wanderer Yes, everything that requires the right mouse button, because the context menu on MacOS and Linux opens on mouse down (since firefox 58 there is a property to change this)
