### ISSUE TITLE
Switch between tabs using mouse scroll wheel

### ISSUE THREAD

**Issue by DeBilbao** [Robbendebiene/Gesturefy#84] opened 2017-11-14 16:15 UTC
Until the updated Firefox Quantum I was using FireGestures to speed up my browser use, and I've found easy to get the equivalence using Gesturify, with only one annoyance that is very useful to me.

Activating rocket gestures, I was able to switch between tabs using the mouse scroll wheel, but I'm not able to do the same using Gesturify.

In FireGestures there was an option called "Tab wheel gestures" to switch between bars when scrolling, but I can't find it in Gesturify.

**Comment by Robbendebiene** [comment] 2017-11-14 16:24
I guess this is what you mean: https://github.com/Robbendebiene/Gesturefy/issues/40 which is impossible with the new API.
The closest you can get is switching tabs with wheel gestures.

**Comment by DeBilbao** [comment] 2017-11-14 16:36
This happened too in Google Chrome and for me was one of the main stoppers for switching to it from Firefox.

How would you configure the tab switching to be similar?

**Comment by Robbendebiene** [comment] 2017-11-14 16:42
Go to Extras, enable wheel gestures and select "next tab" and "previous tab" for wheel up/down. Now if you hold down your specified mouse button on your the current webside and scroll up or down, you should switch to the next/previous tab. However you will notice a delay if the tab/webside isn't already loaded.

**Comment by Thelgow** [comment] 2017-11-15 00:36
I see it also doesnt seem to let us do anything on system pages? I can wheel scroll around but once I hit an about:newtab or even the Extensions options page I cant do a damn thing.

**Comment by Robbendebiene** [comment] 2017-11-15 09:16
Yeah, as far as I know mozilla did this for security reasons, because some pages can run priviledged browser code, which extensions should not be able access.

**Comment by nachoparker** [comment] 2017-11-15 11:13
That's sad, it was a fantastic feature

**Comment by JimboMonkey1234** [comment] 2017-11-16 03:32
I'm primarily interested in this for use with Tree Style Tabs. This issue and the [resulting change](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#override-reaction-for-mouse-wheel-rotation-on-the-vertical-tab-bar) makes me think it's possible: treestyletab/issues#1399

**Comment by Robbendebiene** [comment] 2017-11-16 09:48
@JimboMonkey1234 Yeah, for the vertical tab bar, which is a sidebar that you can fully control in contrast to the browser's tab bar.

**Comment by Robbendebiene** [comment] 2017-11-21 22:38
Duplicate of #40

**Closed by Robbendebiene** 2017-11-21 22:38 UTC
Labels: duplicate

**Comment by gtron** [comment] 2018-04-19 05:34
@DeBilbao: I found a good solution here: 

https://forum.manjaro.org/t/howto-enable-tab-switching-in-firefox-using-mouse-wheel/39954
