### ISSUE TITLE
Gesturefy 3.0.0 not working

### ISSUE THREAD

**Issue by jefferysmall** [Robbendebiene/Gesturefy#472] opened 2020-06-05 17:14 UTC
Gesturefly 3.0.0 with Firefox 77.0.1 on Windows 10.

The new Gesturefly 3.0.0 is working fine with Firefox on my Xubuntu and on another Windows 10 laptop, but for some reason none of the gestures are working on this particular version of Firefox/Windows 10 running in a VM on my Xubuntu machine.  Previous versions of Gesturefly always worked.  I noticed that the gesture titles are not showing up on the gesture page.  I uninstalled the add-on, exited and restarted Firefox, and reinstalled the add-on but nothing improved.  The Gesture page remains as shown and the gestures do not work, even though this does not happen on the other Windows 10 machine.

Any thoughts?

![gesturefly](https://user-images.githubusercontent.com/36275594/83904572-f2a05600-a714-11ea-8042-98a22a0a5bf9.jpg)

**Comment by jefferysmall** [comment] 2020-06-05 17:36
Immediately after posting the info above, I discovered that the problem had migrated to all other instances of Firefox/Gesturefly on every platform and gestures have all stopped working with a setup screen as seen above.  Clearing the Firefox cache had no effect.  Every time I reinstall Gesturefly, it pick up the previous settings and gestures.  I think I need to nuke the settings and start over, but I cannot locate the settings in the Firefox profile directory.  Any suggestions what to do next?

**Comment by jefferysmall** [comment] 2020-06-05 17:39
Also: The red gesture lines are appearing on the screen, but the gestures commands are not executed.

**Comment by Itchiii** [comment] 2020-06-05 18:24
Since no titles appear among your gestures, your commands do not seem to have been taken over. This also means that no gesture will work because no command is assigned.
 
**Maybe it is enough to edit the gestures and reassign the commands.**

If that doesn't help, you can reset your settings and gestures under "About". This restores the default configuration of Gesturefy. 

But since we can't understand your problem yet, it would be nice to keep your current state on one platform. Robbendebiene might have some technical questions for you :)

**Comment by Rot10Crotch** [comment] 2020-06-05 18:35
Can also report that Gesturefly 3.0 is not working with FF 77.0.1 in windows 10 64 bit on all 6 of the PCs in my house.

**Comment by jefferysmall** [comment] 2020-06-05 19:32
Itchiii, good suggestion to reassign commands.  I just tried that and no commands appear when I click on the Command box or the "menu" icon in that box!  Hopefully this points closer to the problem.  What really confuses me is that this all worked right after I upgraded, but then something happened and it broke.  Other than checking/upgrading on the Windows platforms, I don't know what else could be responsible.

By the way, does this add-on specifically have to use the sync function or does that happen automatically now with all extensions?  As soon as I changed a motion assignment, I an (was) seeing it on all platforms immediately.  I ask because I want to use the middle-mouse button for my Linux setup, but set the right-mouse button on the laptop which has a scroll wheel and don't want that one setting to propagate.

![gesturfly2](https://user-images.githubusercontent.com/36275594/83915359-ec67a500-a727-11ea-8d0f-4afff7560aa4.jpg)

**Comment by Itchiii** [comment] 2020-06-05 19:52
Can you please open the console (Ctrl+Shift+J), then reload the addon page, try to open the command bar and then take a picture from the console and upload it here?

And could you please export your settings and upload them here? (About -> Backup)

Settings, gestures and blacklisted websites are synced if Firefox sync is enabled. Otherwise you could transfer your settings via Backup and Restore.

**Comment by jefferysmall** [comment] 2020-06-05 20:48
Here is the console output.  The first three messages were generated when reloading the Firefox Addon page.  The second set of three when the Gesturefly Setup page was displayed.

![FF_Console](https://user-images.githubusercontent.com/36275594/83921295-e88d5000-a732-11ea-88d3-58fbf4caea8d.png)

Here is the JSON file generated by the Gesturefly backup.


[Gesturefy_Backup.txt](https://github.com/Robbendebiene/Gesturefy/files/4738428/Gesturefy_Backup.txt)

**Comment by FranzHoffmann** [comment] 2020-06-05 22:55
I had the same issue with Firefox 77.0.1 on Ubuntu: Gestures did not work, and I can not reassign the commands because no commands appear.

But I could delete the existing gestures and create new ones, and that works.

**Comment by gongminmin** [comment] 2020-06-06 04:14
Same here on Firefox 77.0.1 on Windows 10. Couldn't choose command in the Gestures settings. Have to remove the gesture and create a new one. Old gestures are all lost.

**Comment by thebjorn** [comment] 2020-06-06 09:58
I can verify all symptoms (lines showing up, no gestures working, not being able to assign gestures) on win10 firefox 78.0b3 (64-bit) and 77.0.1 (64-bit).

**Comment by sharpless** [comment] 2020-06-06 10:53
I think the problem is not that the gestures do not work, it is that the commands are not connected to them.

**Comment by thebjorn** [comment] 2020-06-06 14:03
I added a screen shot of a quick debugging session.  It seems that the Command ctor expects a string but gets a `{name: {name: string, ..}}` object at some point.

**Comment by jefferysmall** [comment] 2020-06-06 16:25
Yep, same here.  I deleted them all and recreated them on the Linux box and they are now working.  Next I'll check out the Windows platforms where these should have been synced overnight.

**Comment by jefferysmall** [comment] 2020-06-06 17:15
The syncing with Firefox is a real problem.  After getting the gestures to work on the Linux platform, they stopped working again.  I believe this was due to the faulty settings being stored on the other two syncing Windows platforms.  After clearing out all settings on all platforms and starting over, I was able to set gestures on the Linux platform.  Eventually these synced to the Windows 10 platform running in a VM on this box.  So syncing can cross-pollinate bad setting and cause problems.  Just an FYI for others with multiple installations of Firefox.

As I said above, I use a standard three-button mouse on my main system and use the middle mouse button for gestures, but would prefer the right mouse button on the laptop because of the scroll wheel.  This setting is now being propagated with the sync to all platforms.  If some sort of "lock" feature could be applied to lock the button selection on each instance of Firefox, it would be great. 

Thanks for everyone's help in getting this working.

**Comment by Robbendebiene** [comment] 2020-06-06 22:12
For the next 2 days I'm unable to read all the bug report. For users who have problems with their settings please look here: https://github.com/Robbendebiene/Gesturefy/issues/480
Sorry for the inconvenience.

**Comment by lovezk** [comment] 2020-06-08 04:24
> 
> 
> Can also report that Gesturefly 3.0 is not working with FF 77.0.1 in windows 10 64 bit on all 6 of the PCs in my house.

me too.

**Comment by froooze** [comment] 2020-06-09 19:37
Gesturefy 3.0.1, did not fix this

**Comment by Robbendebiene** [comment] 2020-06-10 11:00
The snyc problem should be fixed with version 3.0.1. This wont fix your config if it is corrupted but the config should no longer get corrupted on sync.

If you config got corrupted please look here: #480

**Closed** 2020-06-22 11:18 UTC
Labels: bug
