### ISSUE TITLE
Scroll gestures not working in some areas of the page

### ISSUE THREAD

**Issue by Udayraj123** [Robbendebiene/Gesturefy#303] opened 2018-06-12 11:18 UTC
### Describe your matter in detail
Steps to reproduce:
1. Open https://about.disqus.com/disqus-demo-page or any page containing disqus comments section
2. Scroll & wait for comments section to load
3. Try scroll gesture in the area, it doesn't work. (see screenshot).

(possibly) Related bug: https://github.com/Robbendebiene/Gesturefy/issues/28
^ It isn't working in the above issue link also: https://www.phonetoday.it/recensione-xiaomi-amazfit-bip 

### Screenshots or further assistance
![screenshot from 2018-06-12 16-47-19](https://user-images.githubusercontent.com/16881051/41287443-551ee250-6e60-11e8-9eea-f171d6e40b01.png)
Scroll to top not working.
![screenshot from 2018-06-12 16-47-26](https://user-images.githubusercontent.com/16881051/41287444-555ef1f6-6e60-11e8-9921-a82c87b8267f.png)
Scroll Down not working.

Conf file(if required): [Gesturefy settings.json on github](https://raw.githubusercontent.com/Udayraj123/awesome-confs/master/Firefox/Gesturefy%201.2.0%20Sat%20Mar%2003%202018.json)

### Your System
- Operating system: `lsb_release -irc` : Ubuntu 16.04
- Firefox version: 60.0.1
- Gesturefy version: 1.2.2

**Comment by Itchiii** [comment] 2018-06-13 19:09
Hey. Thanks for the detailed description.

The problem occurs because an iframe is used for the comments.
An iframe is a external site in the current.
And this area is not scrollable because the full height is used without a scrollbar.

**Comment by WebFreak001** [comment] 2020-02-08 13:37
same problem when trying to scroll in a shadow dom (custom elements)

**Comment by Robbendebiene** [comment] 2020-02-23 10:30
@WebFreak001 I should be able to fix the problem for custom elements, but frames are still a challenge (even though there are possible solutions).

**Comment by Robbendebiene** [comment] 2020-06-04 18:52
Some fixes for this have been added with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0). I'll close this even though the problem is not entirely solved.

**Closed by Robbendebiene** 2020-06-04 18:52 UTC
