### ISSUE TITLE
Is it possible support gestures on all kinds tabs?

### ISSUE THREAD

**Issue by Ninjo79** [Robbendebiene/Gesturefy#175] opened 2017-11-28 09:42 UTC
On tabs: - about:addons
              - Unable to connect Firefox can’t establish a connection to the server …
              - example website: [https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/](url)
              - all tabs
I can't use gesture on these tabs.
Thank you for answer.

**Comment by uegajde** [comment] 2017-11-28 11:52
it is not possible currently.
although there is a workaround for AMO (read #157)

this is caused by the limitation of WebExtension.
WebExtension is different from previous API in the concern of security and compatibility.
As a result, addons cannot access Firefox internal things and protected website (such as AMO)

please read the readme or description on AMO
also, this problem is already discussed, you can read previous issues #5 #6 #157

**Comment by uegajde** [comment] 2017-11-28 11:58
it would be possible if the following bugs be solved in the future .

https://bugzilla.mozilla.org/show_bug.cgi?id=1334918
https://bugzilla.mozilla.org/show_bug.cgi?id=1270412
https://bugzilla.mozilla.org/show_bug.cgi?id=1269456

**Comment by Ninjo79** [comment] 2017-11-28 12:23
And that bugs are in firefox 57?

**Comment by uegajde** [comment] 2017-11-28 12:59
yes, they are in Fx57

be aware, although it is named "bug", it doesn't mean anything wrong in software. 
the "bug" in bugzilla is like "issues" in Github, a discussion unit for a issue

the three are discussing the possibility of addons work on privileged pages
one has been rejected, two are still under discussion and have no specific conclusion yet

**Comment by Ninjo79** [comment] 2017-11-28 13:00
Ok thank you I will be wait.

**Comment by Robbendebiene** [comment] 2017-11-28 13:52
@uegajde Thank you for your support and your detailed explanations. You nailed it :)
I'm closing this, since this was asked many times before.

**Closed by Robbendebiene** 2017-11-28 13:52 UTC
