### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ygoe** [Robbendebiene/Gesturefy#408] opened 2019-07-11 08:20 UTC
### Describe your matter in detail
On all websites, all right-mouse-button gestures have no effect anymore (haven't configured other gesture types). The gesture trail is visible but nothing happens. This add-on does absolutely nothing anymore but painting the page. "privacy.resistFingerprinting" is at its default value false. Add-on settings look as usual.

### Your System
- Operating system: Windows 10
- Firefox version: 68.0
- Gesturefy version: 2.1.1

**Comment by ygoe** [comment] 2019-07-11 12:09
Restarting Firefox didn't change anything.

I went to addons.mozilla.org and uninstalled this, then installed the previous minor version 2.0.4. That worked immediately (after refreshing the page to test). Then I tried with 2.1.1 again and now it also works. Looks like my installation was damaged by an update and reinstalling fixed that.

**Comment by Robbendebiene** [comment] 2019-07-13 08:48
Hi, thanks for the report. Since you got it somehow fixed and the issue is not reproducible so far nor have I any console logs I'm closing this issue for now.

**Closed by Robbendebiene** 2019-07-13 08:48 UTC
