### ISSUE TITLE
Feature Request: Search selection in One-Click-Search-Engine

### ISSUE THREAD

**Issue by extraterrestrial212** [Robbendebiene/Gesturefy#211] opened 2017-12-12 22:41 UTC
FireGestures had the ability to select a text and pop up a selection dialog with all your One-Click-Search-Engines. This way you were able to search for the term e.g. in youtube. Right now in Gesturefy only google is possible, but maybe that can be implemented?

**Comment by Robbendebiene** [comment] 2017-12-13 08:55
Duplicate of #99

**Closed by Robbendebiene** 2017-12-13 08:55 UTC
