### ISSUE TITLE
Implement horizontal scroll functions

### ISSUE THREAD

**Issue by bwucke** [Robbendebiene/Gesturefy#401] opened 2019-07-01 09:20 UTC
One of features I miss from older 'gesture' extensions is the ability to attach 'horizontal scroll' functions (scroll left, scroll right) to the middle button wheel rocker. If, for example, viewing a very big image (larger than the window) normal scroll wheel movement moves up/down, and turning the wheel while it's depressed scrolls left/right. Gesturefy only provides scroll up/down, no horizontal scrolling.

**Comment by Robbendebiene** [comment] 2019-07-04 07:48
Duplicate of #221

**Closed by Robbendebiene** 2019-07-04 07:48 UTC
