### ISSUE TITLE
After executing “Open link in new tab”, rolling wheel causes zooming.

### ISSUE THREAD

**Issue by duyanning** [Robbendebiene/Gesturefy#505] opened 2020-06-17 04:02 UTC
### Your System
- Operating system: win10 version: 1909   os build: 18363.900
- Firefox version: 77.0.1 (64-bit)
- Gesturefy version: 3.0.2

**Comment by ysu2** [comment] 2020-06-17 04:54
Same issue.  Not sure why, it has started with the latest version of firefox.  Mighty annoying.
Is there any chance of finding a solution?
Thanks!

**Comment by Robbendebiene** [comment] 2020-06-17 08:28
Do you have any other add-ons installed? This issue sounds very similar to: https://github.com/Robbendebiene/Gesturefy/issues/499

**Comment by duyanning** [comment] 2020-06-17 11:22
> 
> 
> Do you have any other add-ons installed? This issue sounds very similar to: #499

Yes!
I have "Zoom Page WE" installed (https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/reviews/ )

If I disable "Zoom Page WE", the bug disappears.

**Comment by ysu2** [comment] 2020-06-18 01:28
Hm...right, I had zoomPageWE as well, and similarly, diabling it fixes the issue; thanks!  Let's contact zoompageWE for a fix :)

**Comment by Robbendebiene** [comment] 2020-06-18 08:37
Okay good. I'm closing this as a duplicate then :)

> Let's contact zoompageWE for a fix :)

It's my fault (sort of). Will be fixed with the next release.

**Comment by Robbendebiene** [comment] 2020-06-18 08:38
Duplicate of #499

**Closed by Robbendebiene** 2020-06-18 08:38 UTC
Labels: duplicate
