### ISSUE TITLE
Reopen closed tab works in wrong window

### ISSUE THREAD

**Issue by jlvermeulen** [Robbendebiene/Gesturefy#541] opened 2020-09-12 09:29 UTC
### Describe your matter in detail

When I use the reopen closed tab gesture in a private window, sometimes closed tabs are opened on the main (non-private) window. This is not a new issue, it has been happening since at least a few versions ago. It doesn't seem to happen when I use something like Ctrl + Shift + Tab, but as the behaviour is not consistent, I can't really be sure. It does not seem to be tied to a specific website.

To be clear, it's not that the closed tab from my private window is opened in my normal window. Rather, the reopen closed tab operation is executed on the normal window, although strangely enough it's usually not the most recently closed tab that gets reopened.

Update: It doesn't seem to be a problem specific to private windows. I just tried to reopen a closed tab in my only window, and instead it reopened a window I closed hours ago.

### Your System
- Operating system: Windows 10
- Firefox version: 80.0.1
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment] 2020-09-16 19:35
> Update: It doesn't seem to be a problem specific to private windows. I just tried to reopen a closed tab in my only window, and instead it reopened a window I closed hours ago.

@jlvermeulen You are right. This is a common problem, which happens from time to time. It occurs since the first release of Gesturefy. However I'm not able to fix it since it's a Firefox bug.

There has been several bug reports on bugzilla and at least one of them is probably causing the described issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1538119
https://bugzilla.mozilla.org/show_bug.cgi?id=1399147
https://bugzilla.mozilla.org/show_bug.cgi?id=1408575

As a partial workaround I added an option to the "Restore tab" command which limits the restored tabs to the current window (https://github.com/Robbendebiene/Gesturefy/issues/236).

**Comment by jlvermeulen** [comment] 2020-09-16 20:38
@Robbendebiene that does seem to be the issue, as I do have Firefox set to restore the previous session on startup.

Btw the "current window only" option was on for me, but this was still happening.

**Comment by Robbendebiene** [comment] 2020-09-17 08:36
> Btw the "current window only" option was on for me, but this was still happening.

Yeah sadly it doesn't really prevent the issue. Probably because Firefox messes up the window id's and therefore tells Gesturefy that the tab belongs to the current window when it actually doesn't.

**Comment by byzod** [comment] 2021-12-15 14:18
In my situation the tab that was restored incorrectly is always the log window of ublock origin, I believe there must be some sort of pattern in it

But sadly I still didn't found a way to reproduce it :(

It happens pretty rare actually, maybe once per 2~3 days

I can't active profiler all day and wait for it, any idea to "capture" this bug?

**Comment by Robbendebiene** [comment] 2021-12-18 08:57
@byzod Honestly, I don't have a good idea. I think it's impossible to capture it from an extension point of view, because extension developers only get an arbitrary ID with some details. Apparently these details are correct, but wrongly executed/restored by Firefox.

**Comment by Robbendebiene** [comment] 2024-09-16 14:54
Closing as the bug should be fixed according to https://bugzilla.mozilla.org/show_bug.cgi?id=1538119

**Closed by Robbendebiene** 2024-09-16 14:54 UTC
Labels: external
