### ISSUE TITLE
Gesturefy is not work in some page

### ISSUE THREAD

**Issue by Tomsu2016** [Robbendebiene/Gesturefy#281] opened 2018-04-06 14:51 UTC
In somg setting page, i can't use gesture, such as about:* .
firefox 52.7.3 32bit
Gesturefy 1.1.9

**Comment by Robbendebiene** [comment] 2018-04-06 20:16
Please read either the [addon description](https://addons.mozilla.org/de/firefox/addon/gesturefy/?src=search) or [here](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md).

**Comment by Robbendebiene** [comment] 2018-04-06 20:16
Duplicate of https://github.com/Robbendebiene/Gesturefy/issues/5

**Closed by Robbendebiene** 2018-04-06 20:16 UTC
Labels: duplicate
