### ISSUE TITLE
touchscreen support

### ISSUE THREAD

**Issue by nosferatum23** [Robbendebiene/Gesturefy#191] opened 2017-12-02 11:25 UTC
All new gestures addons including Gesturefy do not work with touch screen. I can't use any on my MS Surface. It worked perfectly with firegestures though

**Comment by Robbendebiene** [comment] 2017-12-02 13:23
There is already an [issue](https://github.com/Robbendebiene/Gesturefy/issues/98) addressing this problem, please write there. Also provide more detailed explanation how touch should work/worked for you previously.

**Comment by Robbendebiene** [comment] 2017-12-02 13:23
Duplicate of #98

**Closed by Robbendebiene** 2017-12-02 13:23 UTC
Labels: duplicate
