### ISSUE TITLE
Save picture

### ISSUE THREAD

**Issue by netseawolf** [Robbendebiene/Gesturefy#289] opened 2018-05-13 12:13 UTC
### Add choice in gesture SAVE PICTURE
Add SAVE PICTURE AS
because save picture only do not remember the last saved folder for a website
and "Save picture as" have this function under Firefox and in this case the last saved directory is used

### Your System
- Operating system: Win 10
- Firefox version: 59.0.3
- Gesturefy version: 1.2.2

**Comment by Itchiii** [comment] 2018-05-14 07:37
Unfortunately, this is currently not possible due to API limitations. This is described in detail here: #145

**Comment by Robbendebiene** [comment] 2018-05-17 17:05
Duplicate of #145

**Closed by Robbendebiene** 2018-05-17 17:05 UTC
Labels: duplicate
