### ISSUE TITLE
Reopen closed tab sometimes reopens wrong tab

### ISSUE THREAD

**Issue by byzod** [Robbendebiene/Gesturefy#629] opened 2021-12-12 04:17 UTC
### Describe your matter in detail

I use a gesture for "reopen closed tab" and config it to "current window only" (not sure the exact word in English but you know the option), but SOMETIMES it opens the log window of ublock instead of the tab I just closed.

Since I barely open new window when using firefox so I'm not sure if this bug applies to firefox window too. For me **it's always the log window of ublock**, it looks like this:

I didn't find a way to reproduce it, this bug occurs really randomly

### Screenshots or further assistance

<img width="666" alt="1" src="https://user-images.githubusercontent.com/848607/145700033-931da250-9bd8-4e5c-a66a-e2a42b6c7ac1.png">

### Your System
- Operating system: win 10 home 21h2
- Firefox version: 94b9 developer
- Gesturefy version: 3.2.4

**Comment by jdreesen** [comment] 2021-12-12 23:48
It happens to me, too. I don't use the ublock log window, but sometimes it re-opens a tab in another window than the one I used the gesture in. I haven't noticed any pattern yet, though.

**Comment by byzod** [comment] 2021-12-13 11:39
> It happens to me, too. I don't use the ublock log window, but sometimes it re-opens a tab in another window than the one I used the gesture in. I haven't noticed any pattern yet, though.
> ### Your System
> 
>     * Operating systems: Windows 10 Pro 21H2 & Ubuntu 18.04
> 
>     * Firefox versions: 95 and older
> 
>     * Gesturefy versions: 3.2.4 and older

A difference worth noting is that I never use any gesture in that log window (gesture can't be used in it though since it's protected extension window)

**Comment by Robbendebiene** [comment] 2021-12-13 18:33
Thanks for the detailed report.
Unfortunately this issue exists since the first release of Gesturefy and strikes me too from time to time. This has already been reported here #541 and so far the consensus is, that this is a bug in Firefox itself.
see for example: https://bugzilla.mozilla.org/show_bug.cgi?id=1538119

**Comment by Robbendebiene** [comment] 2021-12-31 13:16
Duplicate of #541

**Closed by Robbendebiene** 2021-12-31 13:16 UTC
Labels: duplicate
