### ISSUE TITLE
New tab page is shortly displayed when using a Search command

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#530] opened 2020-08-04 17:26 UTC
### Describe your matter in detail

I have created a gesture with the "Search selected text" command with focused tab.

The annoying behavior is this:

- If in Firefox options >Home > New Windows and Tabs > New Tabs > Firefox Home (Default), when I make a search, before is opened the Firefox Home page and immediately after, the Google search page;
- If in Firefox options >Home > New Windows and Tabs > New Tabs > Blank Page, when I make a search, before is opened a blank  page and immediately after, the Google search.

I don't understand the reason. 

### Screenshots or further assistance
You can see the problem in this small video:
http://www.filedropper.com/registrazione1_1

### Your System
- Operating system: Windows 10
- Firefox version: 79 and 80 beta
- Gesturefy version: Version: 3.0.6

**Comment by Robbendebiene** [comment] 2020-08-05 08:06
Thanks for the report.
Will be fixed in the next release.

**Comment by happysurf** [comment] 2020-08-06 09:23
Same problem is present also in your great Type to Search extension.

**Comment by Robbendebiene** [comment] 2020-08-06 09:41
Right, thanks for mentioning that :+1:

**Comment by TM1207** [comment] 2020-09-06 18:44
Dear Robbendebiene,

I am sorry for the comment (#536) on the duplicate issue.

There's one more thing I'd like to report.
If I use the [popup] search engine (without QuickDial), the search engine page will appear properly.
However, the text cursor is put in the URL bar, not in the search box. 

I still use Firefox because of Gesturefy. 
Thanks for developing such a nice addon.

**Comment by Robbendebiene** [comment] 2020-09-06 21:32
@TM1207 No need to apologize. You probably didn't know that your issue was related to this one.

> There's one more thing I'd like to report.
> If I use the [popup] search engine (without QuickDial), the search engine page will appear properly.
> However, the text cursor is put in the URL bar, not in the search box.

Do you mean before the actual search result is loaded? If so then this is something I cannot fix. But if you mean after the site/search is loaded then I'm unable to reproduce it. In this case I would need more information. What search engine do you use? Does it happen on all search engines every time?

> I still use Firefox because of Gesturefy.
> Thanks for developing such a nice addon.

Thanks for mentioning that.

**Comment by TM1207** [comment] 2020-09-07 05:43
@Robbendebiene

Thank you for your reply. 

I am sorry I am not good at English and explain.
So I uploaded the video.  (https://youtu.be/pWCJMX2IF48)

For example, if I wanted to search some word,
BEFORE: use [popup] function ->select the "Google" -> just input the word (because the cursor is already in the search box).
Now:      use [popup] function ->select the "Google" -> click the search box (because the focus is in the URL bar) -> then input the word (because the focus is in the URL bar).

Could you fix it? Or is it an impossible issue (=specifications of Firefox)?

**Comment by Robbendebiene** [comment] 2020-09-08 08:26
@TM1207 

Thanks for the video.
It's working fine in Firefox 79, but since version 80 the url bar will be focused That's why I first couldn't reproduce this.
However the fix for this issue will also solve the focus bug.

**Comment by Robbendebiene** [comment] 2020-09-08 17:30
This should be fixed in [Gesturefy 3.0.7](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.7)

**Comment by TM1207** [comment] 2020-09-08 22:21
@Robbendebiene

Thank you for your reply and tremendous efforts.
Now everything is working very well!
I really appriciate you.

**Closed** 2020-09-08 22:26 UTC
Labels: bug
