### ISSUE TITLE
"Save image" action not working on some images

### ISSUE THREAD

**Issue by Cqfuj** [Robbendebiene/Gesturefy#213] opened 2017-12-17 11:57 UTC
On Twitter some images aren't saved with the "save image" action. 
The image url ends with `.jpg:large` and I think the `:large` part is the reason why it's not saved. If the url ends with `.jpg` it works fine though it's not the large version.
The same issue happens with `:small`.

**Comment by Robbendebiene** [comment] 2017-12-17 16:51
Please provide an example url, so I can reproduce the problem.

**Comment by Cqfuj** [comment] 2017-12-17 17:13
```
https://pbs.twimg.com/media/DPgz9RrX0AArk7Q.jpg:small
https://pbs.twimg.com/media/DPgz9RrX0AArk7Q.jpg
https://pbs.twimg.com/media/DPgz9RrX0AArk7Q.jpg:large
```

**Comment by Robbendebiene** [comment] 2017-12-17 17:21
It seems like this bug is already fixied in Firefox 58.

**Comment by Robbendebiene** [comment] 2018-01-27 17:56
I'm closing this, since it's working in the current FF 58.

**Closed by Robbendebiene** 2018-01-27 17:56 UTC
Labels: external

**Comment by Matthewus** [comment] 2018-06-18 13:55
I did, i hope i did it correctly, never used Bugzilla before. [https://bugzilla.mozilla.org/show_bug.cgi?id=1469121](url)
