### ISSUE TITLE
Feature Request: Add a New customized tab setting with Open empty tab one

### ISSUE THREAD

**Issue by Raszlor** [Robbendebiene/Gesturefy#215] opened 2017-12-21 19:15 UTC
Hello there, firstly, nice extension!

it would be cool if in addition to the option to Open empty tab (below the "Link to foreground tab" setting), another option like Homepage URL, so I can personalize the opened page, since firefox blocks the gestures in the new opened tab

Thanks

**Comment by Robbendebiene** [comment] 2017-12-21 19:36
Hey, I always suggest using [New Tab Override](https://addons.mozilla.org/de/firefox/addon/new-tab-override/), it's pretty lightweight and offers a more consistent behaviour than I could do.

**Comment by Robbendebiene** [comment] 2018-01-01 23:00
Duplicate of #56

**Closed by Robbendebiene** 2018-01-01 23:00 UTC
Labels: duplicate
