### ISSUE TITLE
Context menu does not close after a gesture with right mouse button

### ISSUE THREAD

**Issue by mr3bommel** [Robbendebiene/Gesturefy#361] opened 2018-10-29 10:35 UTC
- Operating system: Windows 10 64-bit
- Firefox version: 63.0 64-bit
- Gesturefy version: 2.0.3

Since the update to Firefox 63.0 the context menu does not close after a gesture.
I use the right mouse button for gestures.

![capture_10292018_113245](https://user-images.githubusercontent.com/44570655/47644446-6d36e600-db6e-11e8-8309-2df559166d58.jpg)

**Comment by Robbendebiene** [comment] 2018-10-30 07:43
Hey, other users had a similar issue with Firefox 63. The reason was that dom.event.contextmenu.enabled in about:config was set to false.
(see this issue: https://github.com/Robbendebiene/Gesturefy/issues/345)

**Comment by Tesserakt-company** [comment] 2018-11-04 15:43
Is it possible to undo that. I like that disabled to access files like instagram stories, but opening the context menu for gestures is not really what I want.

**Comment by Robbendebiene** [comment] 2018-11-04 21:14
@Tesserakt-company No, there is no way for Gesturefy to prevent the context menu if you disable this property.

**Comment by Tesserakt-company** [comment] 2018-11-04 21:36
Have they made their API dumber again? I have had this disabled for years and it only shows the context menu since the last update, I wanna say...

**Comment by Robbendebiene** [comment] 2018-11-04 22:45
If that's really the case then they must have changed something. Maybe add-ons weren't affected by this property before the last update.

**Comment by Robbendebiene** [comment] 2018-11-09 16:39
Duplicate of #345

**Closed by Robbendebiene** 2018-11-09 16:39 UTC
Labels: duplicate
