### ISSUE TITLE
Issue when using left click and "drag with 3 fingers" in macOS

### ISSUE THREAD

**Issue by mrdc** [Robbendebiene/Gesturefy#695] opened 2023-12-15 11:11 UTC
### Describe your matter in detail

When selecting text with 3 fingers, Gesturefy fires with it's own actions.

1. Set Tap to Click in macOS
2. Set in macOS Accessibility -> Pointer Control -> Trackpad Options - > Three Fingers Drag
3. Set left click as activation button in Gesturefy
4. Observe the issue: when selecting text with 3 fingers, Gesturefy fires with its actions.

### Your System
- Operating system: macOS 14.2
- Firefox version: 120.0.1
- Gesturefy version: 3.2.10

**Comment by Gixxa42** [comment] 2023-12-21 22:38
I'm on macOS 14.2.1 and Firefox 121 and can't reproduce this. Either FF update or macOS seems to have resolved it.

**Comment by Gixxa42** [comment] 2023-12-22 11:13
I restarted my Mac and I can also reproduce it now. From what I gather this seems like normal behaviour as what the accessibility function in macOS does is simulate a left click to highlight text which triggers the activation of Gesturefy.

Was this an issue prior to 3.2.10? Not sure if there is a way to account for this and add an exception for this case as I would say that the left click simulation does not use a different function of the OS to do the actually "clicking". Maybe someone else with more knowledge of the macOS API can help out to see if there is a different function that is called which in turn could be added into Gesturefy to not fire the action. If there is not I'm afraid I don't see that there could be a fix for this.

**Comment by Robbendebiene** [comment] 2024-01-02 10:10
Sorry for the late reply. Since I do not have a Mac these kinds of issues are always hard to test for me.

I think @Gixxa42 is right with the simulated left click (also thank you for chiming in).

> From what I gather this seems like normal behaviour as what the accessibility function in macOS does is simulate a left click to highlight text which triggers the activation of Gesturefy.

There is a chance that one of the modifier keys might be set as active in this case. Can one of you please send the outputs generated by this site https://codepen.io/Robbendebiene/full/yLwYjKr when doing a normal left click + move and another one for the special three finger "click"?

**Comment by Gixxa42** [comment] 2024-01-02 10:46
@Robbendebiene 

No problem with chiming in, as I know a lot of devs don't have access to a Mac. Just tried the website and the output is the same for the normal click and three finger click:

```
pointerdown:
altKey false
ctrlKey false
metaKey false
shiftKey
false
button 0
buttons 1
composed true
detail 0
isPrimary true
pointerType
mouse pointerId 0
which 1

pointermove:
altKey false
ctrlKey false
metaKey false
shiftKey false
button -1
buttons 1
composed true
detail 0
isPrimary true
pointer Type mouse
pointerId 0
which 0

pointerup:
altKey false
ctrlKey false
metaKey false
shiftKey false
button 0
buttons 0
composed true
detail 0
isPrimary true
pointerType mouse
pointerId 0
which 1
```

If I don't move it's still the same just without the "pointermove:" part.

I did have a little randomness with pointerdown: --> "buttons". When I click normal with mouse or trackpad the value is always 1. While using the three finger "click" this changes to 0 sometimes. There is no pattern to it so it's more of a random thing that happens and I could not predict if the next one would be 0 or 1.

**Comment by Robbendebiene** [comment] 2024-01-02 11:13
@Gixxa42 Thanks for the logs.

> the output is the same for the normal click and three finger click:

If this is the case then unfortunately there is nothing I can do simply because the add-on cannot distinguish the interactions.

> I did have a little randomness with pointerdown: --> "buttons". When I click normal with mouse or trackpad the value is always 1. While using the three finger "click" this changes to 0 sometimes. There is no pattern to it so it's more of a random thing that happens and I could not predict if the next one would be 0 or 1.

This might be caused by the uncertainty of multi finger gestures. The OS has to interpret and sort of predict your desired interaction as one of your fingers will certainly reach the track-pad a little earlier than the others.

**Comment by Gixxa42** [comment] 2024-01-02 11:17
> This might be caused by the uncertainty of multi finger gestures. The OS has to interpret and sort of predict your desired interaction as one of your fingers will certainly reach the track-pad a little earlier than the others.

Indeed, I did not think of that but it makes sense. Thanks for that insight.

**Closed** 2024-01-05 11:10 UTC
Labels: api limitation
