### ISSUE TITLE
Currently Entered Mouse gesture is not overriden by Next/Previous Tab command (Wheel Gesture)

### ISSUE THREAD

**Issue by MusorGaming** [Robbendebiene/Gesturefy#349] opened 2018-09-13 01:19 UTC
I use Wheel Gesture feature (right button to active), Wheel Up or Wheel Down to switch to next or previous tab.
This works fine. And is a very common use of wheel gestures.

The problem is if I have a pending - accidental mouse gesture command entered (right button to activate same as Wheel Gesture), it is executed FIRST, and then followed by Wheel Gesture.
E.g. two actions are executed at once!

What should happen instead is - the entered mouse gesture should be ignored and overriden completely by the Wheel Gesture.

For example, if I press down and hold RMB (that activates mouse gesture input) and accidentaly move mouse slightly to left ( which registers LEFT mouse gesture which is bound to CLOSE TAB command), and then do a Wheel Down while still holding down RMB. What happens is LEFT gesture (close tab) is executed first. And only then WHEEL DOWN is executed and switches to previous tab.

What is expected - the NEXT/PREVIOUS tabs command triggered by WHEELUP/WHEELDOWN overrides everything and all the previous mouse gestures are ignored.

(this is how it works with FireGestures, FoxyGestures, Opera-Presto(back in the day))

Please fix this. E.g. switching to a different tab should clear the pending entered mouse gestures (ignore them).

**Comment by Robbendebiene** [comment] 2018-09-13 07:50
Thanks for the suggestion, but this is already on our list.

**Comment by Robbendebiene** [comment] 2018-09-13 07:51
Duplicate of #123

**Closed by Robbendebiene** 2018-09-13 07:51 UTC
Labels: duplicate
