### ISSUE TITLE
Duplicate gestures for context aware actions

### ISSUE THREAD

**Issue by jgidlow** [Robbendebiene/Gesturefy#30] opened 2017-09-01 13:09 UTC
I would like to be able to assign the same gesture to multiple actions that originates from different contexts/elements. For example, in FireGestures I have a custom script on drag up that checks if the drag started on a link or not and if it was it opens that link in a new tab and if it wasn't it just opens a new tab instead.

Is this something that could be solved in Gesturefy somehow? Either by assigning your own scripts to gestures or by allowing you to define the same gesture for different elements?

**Comment by Robbendebiene** [comment] 2017-09-01 21:38
This seems similar to this issue: https://github.com/Robbendebiene/Gesturefy/issues/17.
And as stated there, I would like to implement this kind of custom chains or hybrid gestures, but due to the small number of usefull combinations I'm not sure if it's worth the effort.

Also I currently do not have a good GUI approach. I would like to keep the gesture input list and just add a little thing which allows to combine certain gestures. If you have any ideas, feel free to share them with me :)

**Comment by jgidlow** [comment] 2017-09-04 06:48
Don't think I can help you with a GUI approach. But the settings UI in Gesturefy is awesome so I'm sure you could figure out a clear way of adding that feature.

One question I have though is why you feel it is important to add something that lets you combine certain gestures in the GUI in the first place? Couldn't the LinkToBackgroundTab/LinkToForegroundTab gestures just work in combination with other defined gestures even if the same gesture is used for them and then just let the check for whether the gesture started on a link or not decide the action?

**Comment by Robbendebiene** [comment] 2017-09-04 09:00
There are 2 main problems:
1. The supression of other actions: If I would allow multiple actions for one gesture, lets say we have LinkToForegroundTab and newTab, then newTab would ALWAYS be executed regardless of whether the first action succeded or not. This is because the check you were talking about is only done inside the action (LinkToForegroundTab) itself and the newTab action has no knowledge about it. However this would be the easiest part to solve.

2. The execution order: If I assign both or say even 3 actions with the same gesture, which one should be executed first? This is the point where I definitely need to add something in the UI. Implementing an internal order is also not that hard, but would require a data structure change of the current config.

I can only repeat my self, I really like the idea, it's an elegant approach, but regardless of the GUI problems there are also some actions were it's difficult to detect if they fail or not.

So I counted through the actions, there are 18 gestures from currently 40 (the current mozilla version contains a little less) which can potentially fail. Only 4 of them were likely to fail (the "open thing in new tab" ones) and for about 5 of them it will be hard to detect if they fail or not.

Are there other combinations you thought of? Or are you also just interested in a hybrid gesture for new tab and link to foreground tab?

**Comment by jgidlow** [comment] 2017-09-05 06:42
Yes, a hybrid gesture for new tab and link to background tab is what I'm missing the most from FireGestures (that and rocker gestures but that's another issue).

I think I understand the implementation problems you are talking about. I was thinking that gestures starting on links would supersede any other defined gestures and just not execute them at all if there are gestures defined for links. But I can see how that could be tricky to implement. 

I don't think it should even be possible to assign the same gesture to 3 different actions like in your example. Unless those three actions clearly starts from different contexts or elements like with links for example. Then execution order wouldn't even be a problem because you would never execute more than one action per gesture.

**Comment by Robbendebiene** [comment] 2017-09-05 08:10
Yeah you are right, there is just one triple combination I can think of:
Open link > Open image > Open tab

For the moment I think I'm going to implement the single hybrid gesture, but will keep the idea in mind for future versions.

So there's just two last question for me, will the hybrid gesture work like the combination described above or will it only work like this: Open link > Open tab
Second, will it open in foreground or background? Maybe I should implement both types.

Btw Rocker gestures are already implemented and will be available in the next version :)

**Comment by Robbendebiene** [comment] 2017-09-11 16:37
Even if it's not exactly the same topic, I'm going to close this as a duplicate of #17 . So for further discussion please use the other issue.

**Closed by Robbendebiene** 2017-09-11 16:37 UTC
