### ISSUE TITLE
Can not work on https://addons.mozilla.org

### ISSUE THREAD

**Issue by linuxunion** [Robbendebiene/Gesturefy#110] opened 2017-11-17 05:41 UTC
It can not work on https://addons.mozilla.org

**Comment by imrn** [comment] 2017-11-17 05:57
No addon is allowed to work on addons.mozilla.org.

**Comment by Itchiii** [comment] 2017-11-17 07:31
You can set `privacy.resistFingerprinting.block_mozAddonManager` to `true` in about:config
For me there's not such an attitude. Others have these.
For more information look here: #6

**Comment by Robbendebiene** [comment] 2017-11-17 07:53
Duplicate of #6

**Closed by Robbendebiene** 2017-11-17 07:53 UTC
Labels: duplicate
