### ISSUE TITLE
Not work Open Home

### ISSUE THREAD

**Issue by godliu** [Robbendebiene/Gesturefy#96] opened 2017-11-16 00:17 UTC
Hello.
I'm using Gesturefy at FF57. I set open home gesture (e.g.↓→), but it seems to not working.

How can I do this?
Thank you.

**Comment by uegajde** [comment] 2017-11-16 08:41
it works fine for me.
does it not work on every page?

**Comment by godliu** [comment] 2017-11-16 09:06
It only on about:blank,new tab page and about:addons page. 
So, this maybe WebExtension's limit...

**Comment by Itchiii** [comment] 2017-11-16 09:27
Yep, it is an api limitation. See the discription of Gesturefy on mozilla:
> The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

And look here for more information: #6 .

**Comment by Robbendebiene** [comment] 2017-11-16 09:38
Duplicate of #5

**Closed by Robbendebiene** 2017-11-16 09:38 UTC
