### ISSUE TITLE
Open the bookmark bar with gestures

### ISSUE THREAD

**Issue by Paul-Hsu-creator** [Robbendebiene/Gesturefy#496] opened 2020-06-12 11:17 UTC
### Describe your matter in detail
**Hope to increase the ability to open the side bookmark bar through gestures**

### Screenshots or further  
![未命名](https://user-images.githubusercontent.com/66828175/84497357-2fee8000-ace1-11ea-9984-be5c71170ab0.png)

### Your System
- Operating system: win 10 home
- Firefox version: 77.0.1 (64bit)
- Gesturefy version:  Gesturefy, Version: 3.0.2

**Comment by Itchiii** [comment] 2020-06-12 11:49
Unfortunately this is not possible due to the API restrictions.

**Comment by Itchiii** [comment] 2020-06-12 11:49
Duplicate of #141

**Closed by Itchiii** 2020-06-12 11:49 UTC
