### ISSUE TITLE
it does not work on "m.blog.naver.com"

### ISSUE THREAD

**Issue by hjSim** [Robbendebiene/Gesturefy#337] opened 2018-08-31 05:40 UTC
### Describe your matter in detail

Hi. i am using Gesturefy on one of the biggest website 'Naver' in South Korea.
Sometimes i open the mobile version of Naver website. But in here, Gesturefy does not work well. When i am using right button of a mouse, tool menu shows up. You can check this in [https://m.blog.naver.com/Recommendation.nhn].
Thank you.

### Your System
- Operating system: Windows 10 Enterprise (1803) x64 Build 17134.228
- Firefox version: 60.0.2
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment] 2018-09-04 17:46
Hey. Its working fine for me, so I cannot reproduce the error. This maybe an incompatibility with another add-on, for example an AdBlocker.

**Comment by Robbendebiene** [comment] 2018-09-05 07:01
@hjSim You are welcome. Could you figure out which add-on exactly causes the problem? Eventhough there is probably no way to fix this in Gesturefy.

**Comment by hjSim** [comment] 2018-09-05 08:40
@Robbendebiene 
It was "Absolute Enable Right Click & Copy". But you don't need to worry about it. Because the addon enables right click on any website so tool menu showed up. Maybe I turned on the 'right click switch' on [https://m.blog.naver.com/Recommendation.nhn]. 
![image](https://user-images.githubusercontent.com/26080616/45081726-cb2ceb80-b132-11e8-8a39-f41d84939b80.png)

**Comment by Robbendebiene** [comment] 2018-09-05 10:08
All right, thanks. I'm closing this issue then.

**Closed by Robbendebiene** 2018-09-05 10:08 UTC
Labels: external
