### ISSUE TITLE
Syncing configuration

### ISSUE THREAD

**Issue by Sh4dow** [Robbendebiene/Gesturefy#233] opened 2018-01-24 07:48 UTC
Is it possible to sync configurations and saved gestures with Firefox sync?

**Comment by Robbendebiene** [comment] 2018-01-24 09:30
It's technically possible and there already is a feature request for this.

**Comment by Robbendebiene** [comment] 2018-01-24 09:31
Duplicate of #100

**Closed by Robbendebiene** 2018-01-24 09:31 UTC
Labels: duplicate
