### ISSUE TITLE
The gesture "Open link in a new tab" (text only) doesn't work

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#531] opened 2020-08-05 18:50 UTC
### Describe your matter in detail

1. Go to this page:
https://ilmondodimaryantony.blogspot.com/2020/08/patrick-kramer-flowers.html

2. Go to bottom page and select the text link: 
www.patrickkramerart.com/

3. The gesture "Open link in a new tab" doesn't work.

### Screenshots or further assistance
See the problem in this short video:
https://streamable.com/iuu2d3

### Your System

 -   Operating system: Windows 10
 -   Firefox version: 79 and 80 beta
 -   Gesturefy version: Version: 3.0.6

**Comment by Robbendebiene** [comment] 2020-08-06 09:40
Thanks for your detailed reports, this makes it very easy for me to reproduce the problem and respond back.

If you include the `/` at the end of `www.patrickkramerart.com/` in your selection, then right click to open the context menu, you will notice that even Firefox will not provide you a context menu entry to open the selected link. However if you only select `www.patrickkramerart.com` Firefox will provide a context menu entry. Technically in both cases it's not a valid URL (We've already talked about this in an older issue here: https://github.com/Robbendebiene/Gesturefy/issues/11 :) ).

However in #526 I decided to follow Firefox's behaviour, even though I'm probably not able to mimic it perfectly. So once this landed every "Link command" will be able to open pure domains like `www.patrickkramerart.com` (excluding the /)

**Comment by happysurf** [comment] 2020-08-06 10:38
Thank you for detailed reply too. 
I will wait for improvements about that.

**Comment by jferter** [comment] 2020-08-08 08:17
In some special pages are completely invalid, such as the settings page of Firefox.
And when the mouse is pointing at any label, it may be convenient to replace the currently displayed open label with the scroll wheel.

**Comment by Robbendebiene** [comment] 2020-08-09 10:14
> In some special pages are completely invalid, such as the settings page of Firefox.

What do you mean by invalid? Gesturefy doesn't even work on the Firefox Settings page, this also applies to any other add-on.

> And when the mouse is pointing at any label, it may be convenient to replace the currently displayed open label with the scroll wheel.

I don't understand this either. What labels are you talking about? Do you mean the command preview of the currently matching gesture? If so what do you mean by:

>  it may be convenient to replace the currently displayed open label with the scroll wheel.

**Comment by jferter** [comment] 2020-08-10 02:05
What do you mean by invalid? Gesturefy doesn't even work on the Firefox Settings page, this also applies to any other add-on.

- I mean, it's just that the page doesn't work.(firfox:about:preferences).Other general pages are normal

**Comment by jferter** [comment] 2020-08-10 02:21
> I don't understand this either. What labels are you talking about? Do you mean the command preview of the currently matching gesture? If so what do you mean by:
> 
> > it may be convenient to replace the currently displayed open label with the scroll wheel.
the fuction is like "focus left\right tab".But it just use the scroll wheel。And when the mouse point  is in a specific area, such as a Tab ,it can change.(sorry,i should have said it more clearly)

**Comment by Robbendebiene** [comment] 2020-08-10 19:46
>  I mean, it's just that the page doesn't work.(firfox:about:preferences).Other general pages are normal

Please read the limitations section of the [add-on description](https://addons.mozilla.org/firefox/addon/gesturefy/) or [here](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting).

> the fuction is like "focus left\right tab".But it just use the scroll wheel。And when the mouse point is in a specific area, such as a Tab ,it can change.(sorry,i should have said it more clearly)

What you are asking sounds like wheel gestures. These can be found in the Gesturefy settings page under "Extras". However scrolling while your mouse is over a tab won't work and is not possible. If this doesn't answer your questions please open a new issue since this has nothing to do with this issue.

**Comment by jferter** [comment] 2020-08-11 08:53
Thank you for your suggestions.

**Comment by Robbendebiene** [comment] 2020-09-08 17:30
This should now work in [Gesturefy 3.0.7](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.7)

**Closed** 2020-09-10 16:32 UTC
Labels: enhancement
