### ISSUE TITLE
Exceptions list

### ISSUE THREAD

**Issue by Eduardofsr** [Robbendebiene/Gesturefy#220] opened 2017-12-28 10:11 UTC
Is possible to define a list with some websites where the addon won't be enabled?

**Comment by Itchiii** [comment] 2017-12-28 19:05
A blacklist for Gesturefy is planned.
Look here: #62

**Comment by Robbendebiene** [comment] 2017-12-29 22:16
Duplicate of #62

**Closed by Robbendebiene** 2017-12-29 22:16 UTC
Labels: duplicate
