### ISSUE TITLE
Doesn't work on some Dropbox pages

### ISSUE THREAD

**Issue by DavidNemeskey** [Robbendebiene/Gesturefy#330] opened 2018-08-17 08:39 UTC
### Describe your matter in detail

Gestures don't work (as in the overlay doesn't even appear) on some Dropbox pages. An example is https://www.dropbox.com/help/billing/cost. It works fine on https://www.dropbox.com/. I know that this add-on has a history with Linux and the right mouse button, but the choice of the gesture button seems to be irrelevant to this issue.

### Your System
- Operating system: Linux Mint 18.3 Cinnamon
- Firefox version: 61.0.1 64bit
- Gesturefy version: 2.0.2

**Comment by Robbendebiene** [comment] 2018-08-27 07:41
Hi, thanks for the report. Unfortunately this suffers from the same bug as https://github.com/Robbendebiene/Gesturefy/issues/258. It's a Firefox bug and you will notice that even the build in screenshot tool is not working there.

**Comment by Robbendebiene** [comment] 2018-08-28 17:04
Duplicate of #258

**Closed by Robbendebiene** 2018-08-28 17:04 UTC
Labels: duplicate
