### ISSUE TITLE
Gesturefy does not working in Firefox Nightly

### ISSUE THREAD

**Issue by azucat2** [Robbendebiene/Gesturefy#687] opened 2023-10-14 13:30 UTC
### Describe your matter in detail

Mouse gestures do not work since Firefox Nightly 120.0a1 (2023-10-13).
Wheel gestures are still working.

### Your System
- Operating system: Windows 11 22H2
- Firefox version: 120.0a1 (2023-10-13), 120.0a1 (2023-10-14)
- Gesturefy version: 3.2.9

**Comment by mattcoz** [comment] 2023-10-14 16:43
I'm seeing the same thing on 2023-10-14

**Comment by Seagist** [comment] 2023-10-14 16:58
I confirm. On Nightly 2023-10-14 the issue is still present.

**Comment by homekeep** [comment] 2023-10-15 09:38
yes, same problem.

**Comment by ZHAY10086** [comment] 2023-10-15 13:15
Same problem on Nightly 2023-10-14

**Comment by tosuke** [comment] 2023-10-15 16:56
It seems that the reason Gesturefy's gestures are no longer available in Firefox Nightly is that getCoalescedEvents can only be used in a Secure Context. You can find more information about this issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1858434.
I confirmed that it became available by turning off the dom.w3c_pointer_events.getcoalescedevents_only_in_securecontext flag on version 2023-10-15.

**Comment by mattcoz** [comment] 2023-10-15 17:13
> It seems that the reason Gesturefy's gestures are no longer available in Firefox Nightly is that getCoalescedEvents can only be used in a Secure Context. You can find more information about this issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1858434. I confirmed that it became available by turning off the dom.w3c_pointer_events.getcoalescedevents_only_in_securecontext flag on version 2023-10-15.

That does the trick! Good to know there's a workaround.

**Comment by mantou132** [comment] 2023-10-16 08:19
This seems to be the bug of Firefox, I have reported

https://bugzilla.mozilla.org/show_bug.cgi?id=1859236

**Comment by Robbendebiene** [comment] 2023-10-23 14:54
According to the [bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1859236) this has been fixed.
Can someone confirm this?

**Comment by Robbendebiene** [comment] 2023-10-23 17:17
@nazar-pc Thanks for testing.

Also thanks to everyone else for narrowing down the problem so quickly, providing a workaround and even reporting it to the Mozilla devs.

Closing this as resolved by https://bugzilla.mozilla.org/show_bug.cgi?id=1859236

**Closed by Robbendebiene** 2023-10-23 17:17 UTC
