### ISSUE TITLE
Toggle bookmark sidebar - action

### ISSUE THREAD

**Issue by Jens1948** [Robbendebiene/Gesturefy#141] opened 2017-11-19 15:41 UTC
Hi, 
i would really appreciate if you could add an 
action to switch the bookmark tree on the left on and off.

Thx in advance!!!
Jens

**Comment by Robbendebiene** [comment] 2017-11-19 16:29
Hey. Sadly this is not possible with the new API at the moement.

**Comment by Robbendebiene** [comment] 2017-11-29 14:26
Duplicate of #101

**Closed by Robbendebiene** 2017-11-29 14:26 UTC
Labels: api limitation
