### ISSUE TITLE
Context menu appears after gesture

### ISSUE THREAD

**Issue by ygoe** [Robbendebiene/Gesturefy#529] opened 2020-08-04 13:58 UTC
### Describe your matter in detail
I'm using the back navigation gesture virtually all the time. Especially when testing my websites, I'm going back to the previous page all the time. It happens increasingly often that after the gesture is complete and the navigation has happened, the page context menu opens on the previous page. Working locally, the pages load very quickly. Especially if the previous page is still in the browser's page cache. Then it's impossible to see any loading activity. The page is just there instantly. Maybe this is a little too fast for this addon? I'm not sure whether this also happens elsewhere. I'll try to pay attention to it.

### Screenshots or further assistance
Well, it's the normal context menu as if you click the right mouse button alone. My back gesture is a simple line to the left with the right mouse button held down.

### Your System
- Operating system: Windows 10
- Firefox version: 79.0
- Gesturefy version: 3.0.6

**Comment by Robbendebiene** [comment] 2020-08-04 16:31
Thanks for the report. To be honest, I experience that bug from time to time too. I just wasn't sure if it affects other people as well.
My theory is, that the code that blocks the context menu from opening is sometimes already unloaded by the browser before the context menu was even opened. I only experience this for the Page Back/Forth commands, probably because switching to a page from the history is the fastest way due to caching (as you already suggested).

However, I think I should be able to fix this.

**Comment by NitWitPea** [comment] 2020-08-26 01:23
same issue, the context menu comes up instead of drawing my line quite often

**Comment by byzod** [comment] 2020-10-25 09:01
Add a line `user_pref("dom.event.contextmenu.enabled", true);` to `user.js` in your profile, it was reset to false by unknown source time to time, might help

**Comment by ygoe** [comment] 2020-10-25 13:34
@byzod Not sure what that would cause. But you should better just remove that line entirely. true is the default value (can be seen in about:config), and that's already set for me.

**Comment by byzod** [comment] 2020-10-25 13:50
> 
> 
> @byzod Not sure what that would cause. But you should better just remove that line entirely. true is the default value (can be seen in about:config), and that's already set for me.

Yes it was, but when I encountered the problem I found the cause in pref.js by binary search. When I reset it to true, it was set to false again few minutes later by unknown extension or something else so I have to fix it in user.js...

**Comment by ygoe** [comment] 2020-10-25 13:56
Still, that must be specific to your profile. Maybe another add-on.

**Comment by Robbendebiene** [comment] 2020-11-27 23:19
I'm still not able to reproduce this issue reliably. It hasn't even occurred to me in the last few months. So if anyone can reproduce it reliably, please post the steps here. If not it might be a race condition.

**Comment by ygoe** [comment] 2020-11-28 13:21
I, too, can't remember when I've seen this the last time. I think I remember it happened once within the last couple months (human brains are terrible at remembering), but certainly less often than in the past.

**Comment by Robbendebiene** [comment] 2021-03-24 12:08
Just for reference:

**Report:**
> I set the Rocker gesture "Right mouse click" [Left to Right] for opening a new tab and having no issue for months or so. (it seems to be strange after I read the comments above!?)
> But from recent weeks or a month at most, it happens to popup contextmenu on the opened tab. (regardless of about:blank, about:home or any web pages)
> It sometimes happens, and it might depend on the timing of the mouseup of the right click.
> 
> How to reproduce:
> 
>     set the Rocker gesture "Right mouse click" [Left to Right] for opening a new tab
>     visit some gesturable web page
>     fire the Rocker gesture "Right mouse click" [Left to Right]
>     contextmenu happens to popup on the new tab (depends on the timing of the mouseup of the right click)
> 
> Does it cause the issue?
> 1605006
> (I don't have any clues but I just found the commit which has 'contextmenu' on recent versions)
> 
> It looks similar but my case is from recent weeks.
> #529
> 
> It could be occurred by Firefox's update, but I don't have any idea.
> (macOS Catalina 10.15.7, Firefox Beta 87.0 and now updated to 88.0, Gesturefy 3.1.1)


**My answer:**
> @knoajp If it only occurs sometimes then this is probably the same issue as #529. It's a race condition where the new tab is opened before the context menu event fired. I didn't come up with a good solution yet.

**Comment by Robbendebiene** [comment] 2021-06-22 14:55
I'm closing this issue for now, since it seems to be resolved. If anyone encounters the bug again feel free to reopen it (or leave a comment).

**Closed by Robbendebiene** 2021-06-22 14:55 UTC
Labels: bug

**Comment by sappjw** [comment] 2022-04-06 14:16
Apparently the fix for this issue is recommended against in the [Mozilla STIG, finding V-251556](https://www.stigviewer.com/stig/mozilla_firefox/2021-12-01/finding/V-251556), so this bug exists for those of us who have browsers locked by administrators in this way. Not sure if there's anything you can do about this.

> A website may execute JavaScript that can remove or replace context menus/pop-up menus. This can help disguise an attack. Set this preference [dom.event.contextmenu.enabled] to "false" so that web pages will not be able to affect the context menu event.

**Comment by Robbendebiene** [comment] 2022-04-06 16:08
@sappjw Since Gesturefy mostly operates on the same technology as websites do, it heavily relies on the `preventDefault` functionality to suppress the context menu. So with the current API there is nothing I can do about this.

I guess the best choice for those who cannot or don't want to allow this, is to use the middle mouse button as the gesture activation button.

**Comment by sappjw** [comment] 2022-04-06 16:53
Good point, thanks for the idea.
