### ISSUE TITLE
blacklist for sites

### ISSUE THREAD

**Issue by shinji2009** [Robbendebiene/Gesturefy#297] opened 2018-05-28 10:04 UTC
hi
is it possible to make a blacklist (and maybe even whitelist) settings for Gesturefy? to make it not work/work only on certain sites?
thank you

**Comment by Itchiii** [comment] 2018-05-28 13:12
Hey.
A blacklist comes with the next major release (2.0). It is already implemented on the beta branch.

**Comment by Itchiii** [comment] 2018-05-28 13:13
Duplicate of #62

**Closed by Itchiii** 2018-05-28 13:13 UTC
