### ISSUE TITLE
Doesn't or partially works after latest update.

### ISSUE THREAD

**Issue by MrBalint91** [Robbendebiene/Gesturefy#719] opened 2024-06-15 08:02 UTC
### Describe your matter in detail
I'm using  Gesturefy, Version: 3.2.12 with Mozzila 127.0 (64-bit).
Gesturefy either doesn't work at all, or sometimes, randomly registers my gestures once, then won't do it again (just brings up the right-click mouse options, as it is the default). 
Even when it randomly registers the gestures, the visuals from the plugin aren't there. 
I went trough the troubleshooting guide, I restarted my browser, I reinstalled Gesturefy, i turned off other add-ons.

**Comment by Robbendebiene** [comment] 2024-06-17 15:30
Some additional questions:
- Have you tried Gesturefy on a fresh Firefox profile?
- Have you tried resetting Gesturefy (Settings page > About)? (backup your config first)
- Has Gesturefy worked before?

Since I cannot reproduce the issue I need you to provide some logs:

1. Enter `about:devtools-toolbox?type=extension&id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D` in your address bar
2. Switch to the "**Console**" tab in the top bar
3. **Clear** the console via the bin icon (because it also shows errors unrelated to Gesturefy)
4. Reproduce the error
5. Head back to the console and copy and paste all outputs into the issue

A screen recording of the problem would also be helpful.

**Comment by Robbendebiene** [comment] 2024-07-03 07:12
Without further information I cannot solve this. Therefore I'm closing this.

**Closed by Robbendebiene** 2024-07-03 07:12 UTC
