### ISSUE TITLE
FF57 Linux: can't use right click at all

### ISSUE THREAD

**Issue by nachoparker** [Robbendebiene/Gesturefy#92] opened 2017-11-15 11:17 UTC
Again, thank you for your great work.

I cannot use the right click for either gestures or wheel gestures.

**Comment by stephanfriedrich** [comment] 2017-11-15 11:50
Pls, dont open tickets which already exists. -_____- 
#87

**Comment by Robbendebiene** [comment] 2017-11-15 12:55
Duplicate of #1

**Closed by Robbendebiene** 2017-11-15 12:55 UTC

**Comment by nachoparker** [comment] 2017-11-15 13:29
sorry, it seemed like a separate issue to me, because they don't work at all for me.

I thought #1 means that they work, but open the context menu as well

**Comment by Robbendebiene** [comment] 2017-11-15 13:32
@nachoparker Ok, I renamed it.
