### ISSUE TITLE
HowTo Open Homepage, if homepage is a local file?

### ISSUE THREAD

**Issue by alphgh** [Robbendebiene/Gesturefy#225] opened 2018-01-10 11:16 UTC
Hi,

I want to use the Open Homepage gesture for opening a local file under windows, e.g. 
      C:/Data/bookmarks.html
I have tried several formats for the Homepage URL entry of the Gesturefy settings (with of without file: prefix), but nothing works.
What is the correct format?

Thanx in advance

**Comment by Robbendebiene** [comment] 2018-01-10 18:09
Duplicate of #189

**Closed by Robbendebiene** 2018-01-10 18:09 UTC
Labels: duplicate
