### ISSUE TITLE
Gesture not working on an image

### ISSUE THREAD

**Issue by SvenYJ** [Robbendebiene/Gesturefy#347] opened 2018-09-09 04:30 UTC
### Describe your matter in detail
**Gesture is not working on an image**. On the same web-page but outside the image it works fine. Example:
https://sok.riksarkivet.se/bildvisning/A0041525_00225?c=0&m=0&s=0&cv=201#?cv=224&z=-444.4171%2C0%2C7632.8343%2C4448

### Your System
- Windows 10 [Version 10.0.17134.228]
- Firefox version: 60.2.0esr (32 bit)
- Gesturefy version: 2.0.3

**Comment by dym-sh** [comment] 2018-09-09 14:41
URL needs auth, pick a different example

**Comment by SvenYJ** [comment] 2018-09-09 15:46
I have tested on ordinary images, and on those Geturefy works fine. Should have tested this before submitting. So the problem is not the image.

You can create your own user, no costs, only need a mail-address. It used to be a pay-service, but now it's free, payed by the Swedish government. They probably just didn't want to change their code and remove login.

I have copied the source-code for the frame below, maybe this will tell you something. But the best is if you create a user.
---

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsviews/0.9.75/jsviews.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/easyXDM/2.4.17.1/easyXDM.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/easyXDM/2.4.17.1/json2.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/3.2.1/es6-promise.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/yepnope/1.5.4/yepnope.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash-compat/3.10.2/lodash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Base64/0.3.0/base64.min.js"></script>
    <script type="text/javascript" src="/universalviewer_1_8_38/lib/bundle.min.js"></script>

    <link href="/universalviewer_1_8_38/lib/uv-css?v=9ttStlxd94gtcFHsrwEU3rYfQq9AVUcEbVXhd_qycME1" rel="stylesheet"/>

    <script data-main="lib/app" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>

    <style type="text/css">
        #app.loading {
            background-repeat: no-repeat;
            background-position: 50% 50%;
            background-image: url(data:image/gif;base64,R0lGODlhEAAQAPIAAAAAAP///zw8PLy8vP///5ycnHx8fGxsbCH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==);
        }
    </style>
</head>
<body>
    <div id="app" class="loading"></div>
    <script type="text/javascript">
        var app = document.getElementById("app");
        var width = window.innerWidth || document.documentElement.clientWidth;
        var height = window.innerHeight || document.documentElement.clientHeight;
        app.setAttribute("style", "width:" + width + "px");
        app.setAttribute("style", "height:" + height + "px");

        (function FixUvLocalStorageProblem() {
            //Kollar om uv.settings i localStorage verkar innehålla uppgifter den inte borde. I så fall raderas den och kommer att återskapas av Universal Viewer.
            var uvSettingsKey = 'uv.settings';
            var uvsettingsJson = localStorage.getItem(uvSettingsKey);
            var uvsettings = JSON.parse(uvsettingsJson);
            if (uvsettings && uvsettings.value && typeof uvsettings.value == 'object' && uvsettings.value.hasOwnProperty('saveUserSettings')) {
                localStorage.removeItem(uvSettingsKey);
                console.log('localStorage problem identifierades och fixades!');
            }
        })();

    </script>
</body>
</html>

________________________________
Från: DYM <notifications@github.com>
Skickat: den 9 september 2018 16:41
Till: Robbendebiene/Gesturefy
Kopia: SvenYJ; Author
Ämne: Re: [Robbendebiene/Gesturefy] Gesture not working on an image (#347)


URL needs auth, pick a different example

**Comment by Itchiii** [comment] 2018-09-09 17:39
### For a better read (Comment by SvenYJ), I could not edit the comment correctly.

I have tested on ordinary images, and on those Geturefy works fine. Should have tested this before submitting. So the problem is not the image.

You can create your own user, no costs, only need a mail-address. It used to be a pay-service, but now it's free, payed by the Swedish government. They probably just didn't want to change their code and remove login.

I have copied the source-code for the frame below, maybe this will tell you something. But the best is if you create a user.

---

```html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsviews/0.9.75/jsviews.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/easyXDM/2.4.17.1/easyXDM.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/easyXDM/2.4.17.1/json2.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/3.2.1/es6-promise.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/yepnope/1.5.4/yepnope.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lodash-compat/3.10.2/lodash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Base64/0.3.0/base64.min.js"></script>
    <script type="text/javascript" src="/universalviewer_1_8_38/lib/bundle.min.js"></script>

    <link href="/universalviewer_1_8_38/lib/uv-css?v=9ttStlxd94gtcFHsrwEU3rYfQq9AVUcEbVXhd_qycME1" rel="stylesheet"/>

    <script data-main="lib/app" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>

    <style type="text/css">
        #app.loading {
            background-repeat: no-repeat;
            background-position: 50% 50%;
            background-image: url(data:image/gif;base64,R0lGODlhEAAQAPIAAAAAAP///zw8PLy8vP///5ycnHx8fGxsbCH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==);
        }
    </style>
</head>
<body>
    <div id="app" class="loading"></div>
    <script type="text/javascript">
        var app = document.getElementById("app");
        var width = window.innerWidth || document.documentElement.clientWidth;
        var height = window.innerHeight || document.documentElement.clientHeight;
        app.setAttribute("style", "width:" + width + "px");
        app.setAttribute("style", "height:" + height + "px");

        (function FixUvLocalStorageProblem() {
            //Kollar om uv.settings i localStorage verkar innehålla uppgifter den inte borde. I så fall raderas den och kommer att återskapas av Universal Viewer.
            var uvSettingsKey = 'uv.settings';
            var uvsettingsJson = localStorage.getItem(uvSettingsKey);
            var uvsettings = JSON.parse(uvsettingsJson);
            if (uvsettings && uvsettings.value && typeof uvsettings.value == 'object' && uvsettings.value.hasOwnProperty('saveUserSettings')) {
                localStorage.removeItem(uvSettingsKey);
                console.log('localStorage problem identifierades och fixades!');
            }
        })();

    </script>
</body>
</html>
```

**Comment by Robbendebiene** [comment] 2018-09-12 08:50
This might be the same problem as described in https://github.com/Robbendebiene/Gesturefy/issues/258

Please follow these steps:
1. visit the problematic page/image
2. open the network analysis via Ctrl + Shift + E
3. reload the page/image via Ctrl + F5 (this bypasses the cache)
4. in the network panel there should be at least one entry with status 200, select/click the first one
5. in the new pnale to the right search for "Content-Security-Policy" (it should be somewhere at the top) and either make a screenshot or post the corresponding value here. If you are not able to find "Content-Security-Policy" then the problem might be something else

**Comment by SvenYJ** [comment] 2018-09-12 10:26
The "Content-Security-Policy":
default-src 'self';script-src 'self' 'unsafe-inline' 'unsafe-eval' iiif.riksarkivet.se lbiiif.riksarkivet.se www.googletagmanager.com www.google-analytics.com static.hotjar.com script.hotjar.com cdnjs.cloudflare.com tagmanager.google.com;object-src 'self';style-src 'self' 'unsafe-inline' tagmanager.google.com fonts.googleapis.com;img-src 'self' data: riksarkivet.se iiif.riksarkivet.se lbiiif.riksarkivet.se www.google-analytics.com stats.g.doubleclick.net lbiiif-riksarkivet-se.proxybib.miun.se lbiiif-riksarkivet-se.ezp.sub.su.se lbiiif-riksarkivet-se.ezproxy.its.uu.se lbiiif-riksarkivet-se.ludwig.lub.lu.se lbiiif-riksarkivet-se.proxy.ub.umu.se lbiiif-riksarkivet-se.proxy.lnu.se lbiiif-riksarkivet-se.e.bibl.liu.se lbiiif-riksarkivet-se.till.biblextern.sh.se/ lbiiif-riksarkivet-se.proxy.library.ju.se lbiiif-riksarkivet-se.www.bibproxy.du.se:8443 lbiiif-riksarkivet-se.ezproxy.ub.gu.se lbiiif-riksarkivet-se.helios.uta.fi iiif-riksarkivet-se.proxybib.miun.se iiif-riksarkivet-se.ezp.sub.su.se iiif-riksarkivet-se.ezproxy.its.uu.se iiif-riksarkivet-se.ludwig.lub.lu.se iiif-riksarkivet-se.proxy.ub.umu.se iiif-riksarkivet-se.proxy.lnu.se iiif-riksarkivet-se.e.bibl.liu.se iiif-riksarkivet-se.till.biblextern.sh.se iiif-riksarkivet-se.proxy.library.ju.se iiif-riksarkivet-se.www.bibproxy.du.se:8443 iiif-riksarkivet-se.ezproxy.ub.gu.se iiif-riksarkivet-se.helios.uta.fi static.hotjar.com script.hotjar.com ssl.gstatic.com www.gstatic.com;media-src 'none';font-src 'self' data: fonts.gstatic.com;connect-src 'self' riksarkivet.se iiif.riksarkivet.se lbiiif.riksarkivet.se in.hotjar.com www.google-analytics.com lbiiif-riksarkivet-se.proxybib.miun.se lbiiif-riksarkivet-se.ezp.sub.su.se lbiiif-riksarkivet-se.ezproxy.its.uu.se lbiiif-riksarkivet-se.ludwig.lub.lu.se lbiiif-riksarkivet-se.proxy.ub.umu.se lbiiif-riksarkivet-se.proxy.lnu.se lbiiif-riksarkivet-se.e.bibl.liu.se lbiiif-riksarkivet-se.till.biblextern.sh.se/ lbiiif-riksarkivet-se.proxy.library.ju.se lbiiif-riksarkivet-se.www.bibproxy.du.se:8443 lbiiif-riksarkivet-se.ezproxy.ub.gu.se lbiiif-riksarkivet-se.helios.uta.fi iiif-riksarkivet-se.proxybib.miun.se iiif-riksarkivet-se.ezp.sub.su.se iiif-riksarkivet-se.ezproxy.its.uu.se iiif-riksarkivet-se.ludwig.lub.lu.se iiif-riksarkivet-se.proxy.ub.umu.se iiif-riksarkivet-se.proxy.lnu.se iiif-riksarkivet-se.e.bibl.liu.se iiif-riksarkivet-se.till.biblextern.sh.se/ iiif-riksarkivet-se.proxy.library.ju.se iiif-riksarkivet-se.www.bibproxy.du.se:8443 iiif-riksarkivet-se.ezproxy.ub.gu.se iiif-riksarkivet-se.helios.uta.fi;child-src 'self' vars.hotjar.com;frame-ancestors 'self';report-uri /WebResource.axd?cspReport=true

**Comment by SvenYJ** [comment] 2018-09-12 11:15
Sorry, closed it by mistake (my first Github experinence....)

**Comment by Robbendebiene** [comment] 2018-09-12 11:19
No problem. Unfortunately it suffers from the same Firefox bug as the issue I've mentioned, so I'll close this as a duplicate of it.

**Closed by Robbendebiene** 2018-09-12 11:19 UTC
Labels: duplicate
