### ISSUE TITLE
Feature request: support clone action

### ISSUE THREAD

**Issue by hpop1994** [Robbendebiene/Gesturefy#285] opened 2018-04-12 05:10 UTC
I use [down-left] for close current tab and focus on left tab, and [down-right] for close current tab and focus on right tab in chrome. But for Gesturefy, I can't make such config becasue there is only on close action right now in the preference page.

**Comment by Robbendebiene** [comment] 2018-04-14 16:13
This will be possible in Gesturefy 2.0, which we are currently working on.
Since this is covered by https://github.com/Robbendebiene/Gesturefy/issues/197 I'll close this one as a duplicate of it.

**Comment by Robbendebiene** [comment] 2018-04-14 16:14
Duplicate of #197

**Closed by Robbendebiene** 2018-04-14 16:14 UTC
Labels: duplicate
