### ISSUE TITLE
[Pop up] Recently closed tabs doesn't work

### ISSUE THREAD

**Issue by Azulmagia** [Robbendebiene/Gesturefy#567] opened 2021-02-11 19:35 UTC
The "[Pop up] Recently closed tabs" isn't working properly, the gesture opens the pop up window but clicking on it doesn't open anything, and the window doesn't disappear afterwards, it stays on screen covering everything underneath and the only way to remove it is to refresh the page.

- Operating system: Windows 10
- Firefox version: 85.0.2 (64 bit)
- Gesturefy version: 3.1.0

**Comment by Robbendebiene** [comment] 2021-02-11 20:06
I cannot reproduce this issue, so can you please post a console log?
If you don't know how to do it, you can find a description here: https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md

You should first clear the console, then produce the bug (perform the gesture) and after that return back to the console.

**Comment by Azulmagia** [comment] 2021-02-11 20:28
This is what I get:

Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103909
    [433]</< moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103909
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103916
    [433]</< moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103916
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103322
    injectDOMSignal moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103322
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103329
    injectDOMSignal moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103329
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. content-state-handler.js:1
    checkIfInjectionNeeded moz-extension://2d6f93cb-791a-441d-8454-5615ded26a8a/scripts/background/app/content-state-handler.js:1
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103909
    [433]</< moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103909
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103916
    [433]</< moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103916
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103322
    injectDOMSignal moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103322
Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103329
    injectDOMSignal moz-extension://13dd4651-dd8c-4032-8ade-57f96ccc4894/public/js/background.js:103329
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. content-state-handler.js:1
    checkIfInjectionNeeded moz-extension://2d6f93cb-791a-441d-8454-5615ded26a8a/scripts/background/app/content-state-handler.js:1

​This is how it looks like, all those pop up windows show the recently closed tabs, clicking on them does nothing and they just pile up without being able to remove them until I refresh the page
![Sin título](https://user-images.githubusercontent.com/78899694/107694575-26a12300-6c75-11eb-8840-99f4c1d33580.png)

​

**Comment by Robbendebiene** [comment] 2021-02-11 21:04
Thanks for the log. However this are "expected" errors at least the following:
`Unchecked lastError value: Error: Frame not found, or missing host permission background.js:103909`
Did you experience the bug in the previous version? Do you have any other extensions installed?

**Comment by Azulmagia** [comment] 2021-02-11 22:23
No, it worked fine in the previous version, it started happening until the most recent update

**Comment by Robbendebiene** [comment] 2021-02-11 23:24
There is another console where errors might be logged. It can be opened via ctrl + shift + I (it will also contain logs from the current webpage). It may be helpful If you could do the same procedure as you did with the the other console. If this still doesn't give me any clues I'll need to send you a modified Gesturefy version in order to properly debug this.
It would also be helpful if you could test Gesturefy on a another clean Firefox profile.

**Comment by Azulmagia** [comment] 2021-02-11 23:55
I get this:

Error de seguridad: el contenido en moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/popup-command-view.html no se puede cargar o enlazar con chrome://mozapps/skin/extensions/extension.svg. 90
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
    initialize moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:27
    handleMessage moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:110
iframe-popup-command-view.js:135:11
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
    initialize moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:27
    handleMessage moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:110
iframe-popup-command-view.js:135:11
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
    initialize moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:27
    handleMessage moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:110
iframe-popup-command-view.js:135:11
Error de seguridad: el contenido en moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/popup-command-view.html no se puede cargar o enlazar con chrome://mozapps/skin/extensions/extension.svg. 1410
Uncaught (in promise) Error: Popup is null undefined
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
    initialize moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:27
    handleMessage moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:110
iframe-popup-command-view.js:135:11
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
    initialize moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:27
    handleMessage moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:110
iframe-popup-command-view.js:135:11
Error de seguridad: el contenido en moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/popup-command-view.html no se puede cargar o enlazar con chrome://mozapps/skin/extensions/extension.svg. 672
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined
Uncaught (in promise) Error: Popup is null undefined

**Comment by Azulmagia** [comment] 2021-02-12 00:05
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
iframe-popup-command-view.js:135:11
    sendPortMessage resource://gre/modules/ExtensionChild.jsm:299
    sendPortMessage self-hosted:1176
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135

**Comment by Azulmagia** [comment] 2021-02-12 00:14
I tried it in another firefox profile and the error still persists.

**Comment by Robbendebiene** [comment] 2021-02-12 09:09
Thanks. This looks promising.

**Comment by Robbendebiene** [comment] 2021-02-12 10:09
Can you please test if the bug persist with the following version: [gesturefy_test.zip](https://github.com/Robbendebiene/Gesturefy/files/5970952/gesturefy_test.zip)

You need to open about:debugging, click "Load Temporary Add-on" and select the zip file. It will overwrite the existing Gesturefy installation until you restart your brwoser. After a restart everything should be back as it was before.
If the error still exists please post another console log like you did the last time. It should contain some additional info now.

**Comment by Azulmagia** [comment] 2021-02-13 00:08
I've been testing with the new version and it worked fine. I restarted the browser and it looked fine in most pages but it sometimes  stopped working randomly. This is what I got from the console log after th restart:

Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en inline ("script-src"). onloadwff.js:71:791213
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en inline ("script-src"). fingerprint-protection.js:343:25
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en data:application/font-woff;charset=utf-8… ("font-src"). 4 textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfChc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfCxc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBxc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfCBc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfABc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfCRc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fChc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fCxc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBxc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fCBc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fABc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fCRc4EsA.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxK.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu7GxKOzY.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu7WxKOzY.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4WxKOzY.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu7mxKOzY.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu5mxKOzY.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu72xKOzY.woff2 ("font-src"). textarea-autosize.esm.js:1
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOUuhp.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOXOhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOXehpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOUehpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOXuhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOVuhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN7rgOX-hpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOUuhp.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOXOhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOXehpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOUehpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOXuhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOVuhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UNirkOX-hpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFVZ0b.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFW50bbck.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFWp0bbck.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFVp0bbck.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFWZ0bbck.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFUZ0bbck.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem8YaGs126MiZpBA-UFWJ0bbck.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OUuhp.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OXOhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OXehpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OUehpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OXuhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OVuhpOqc.woff2 ("font-src").
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en https://fonts.gstatic.com/s/opensans/v18/mem5YaGs126MiZpBA-UN_r8OX-hpOqc.woff2 ("font-src").
Este sitio parece usar un efecto de posicionamiento vinculado al desplazamiento. Esto puede no funcionar bien con panorámica asíncrona; ¡mira https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects para más detalles y para unirte a la discusión sobre herramientas y características relacionadas! 567
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en inline ("script-src"). 2 fingerprint-protection.js:343:25
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
iframe-popup-command-view.js:135:11
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
iframe-popup-command-view.js:135:11
Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
iframe-popup-command-view.js:135:11
Content Security Policy: Las opciones de esta página han bloqueado la carga de un recurso en inline ("script-src"). fingerprint-protection.js:343:25

Uncaught Error: Attempt to postMessage on disconnected port
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135
iframe-popup-command-view.js:135:11
    sendPortMessage resource://gre/modules/ExtensionChild.jsm:299
    sendPortMessage self-hosted:1176
    handleItemSelection moz-extension://8002836b-86ca-4005-9869-9400b534ca5a/core/views/popup-command-view/iframe-popup-command-view.js:135

​

​

**Comment by Robbendebiene** [comment] 2021-02-13 08:58
The error should reoccur if you restart the browser because Firefox will load the old version of Gesturefy. The interesting question is, if you also experience the bug when you temporary load the add-on I attached (I expect that it still doesn't work, but with a new console output I may finally find the source). So can you please do this again:
- open about:debugging#/runtime/this-firefox
- click "Load Temporary Add-on"
- select the zip file
- go to https://example.com/ or another webpage where you've experienced the bug
- open the console via ctrl + shift + I
- try your popup gesture
- post the logs here

btw you can also attach the logs as a txt file.

**Comment by Azulmagia** [comment] 2021-02-13 20:14
I've been testing again with the new add-on, so far the bug hasn't happened. Here's what appears in the log while using the add-on
[console-export-2021-2-13_13-43-1.txt](https://github.com/Robbendebiene/Gesturefy/files/5976449/console-export-2021-2-13_13-43-1.txt)

**Comment by Robbendebiene** [comment] 2021-02-14 14:20
Thanks for the update and the log. I released a new version today which will be available soon. It would be nice if you could report back after the next update (wether it fixed your problem or not).

**Comment by Robbendebiene** [comment] 2021-02-17 17:20
The new version is out. Do you still experience the issue?

**Comment by Azulmagia** [comment] 2021-02-18 23:43
After experiencing the new update for over a day, I haven't encountered the issue anymore. It seems the problem has been fixed. Thanks :)

**Comment by Robbendebiene** [comment] 2021-02-19 08:11
All right thanks for your feedback :)
I'm closing this issue then.

**Closed by Robbendebiene** 2021-02-19 08:11 UTC
