### ISSUE TITLE
Gestures don't work in about: pages

### ISSUE THREAD

**Issue by WatermelonDriveway** [Robbendebiene/Gesturefy#235] opened 2018-01-26 23:52 UTC
about:preferences, about:config, about:addons etc.

I'm on osx running firefox 58

**Comment by Robbendebiene** [comment] 2018-01-27 17:40
Please read the [addon description](https://addons.mozilla.org/firefox/addon/gesturefy/).

**Comment by Robbendebiene** [comment] 2018-01-27 17:40
Duplicate of #5

**Closed by Robbendebiene** 2018-01-27 17:40 UTC
Labels: duplicate
