### ISSUE TITLE
Close tab impacts cursor - Firefox 78.0.1

### ISSUE THREAD

**Issue by 130R** [Robbendebiene/Gesturefy#514] opened 2020-07-03 06:41 UTC
When using a gesture to close a tab I am finding that the mouse cursor (pointer) on the next tab to gain focus retains the arrow icon when hovering over links, rather than changing from arrow to the hand icon as expected. 

Operating system: Windows 10
Firefox version: 78.0.1
Gesturefy version: 3.0.4

Steps to reproduce:

1. Go to youtube.com (I believe any site will work)
2. Note when hovering over any video, or link in the sidebar, that the mouse cursor changes from arrow to hand icon
3. Open any link on the page in a new tab
4. Note the cursor in the new tab behaves as expected
5. Use a mouse gesture to close the new tab
6. The cursor on the original tab (now the only tab open) does not behave as expected and retains the arrow icon when hovering over links. Moving the cursor over the URL bar (off the top of the page) will change the behaviour back to expected

Just FYI - I noticed the same behaviour with a different mouse gesture extension as well

**Comment by tanrak** [comment] 2020-07-03 07:34
I can confirm this.

**Comment by tworepetae** [comment] 2020-07-03 07:53
Yep, same here. It's hard to reproduce but my cursor is often stuck with the arrow icon and won't change to pointing finger when hovering over links. Pulling it away from Firefox window and then back temporarily fixes the issue. 
It looks like disabling Gesturefy fixes the issue for good so it looks like the culprit.

**Comment by Robbendebiene** [comment] 2020-07-03 08:35
Thanks for the report. I also sometimes experience the problem but I cannot reproduce it reliably.

> Just FYI - I noticed the same behaviour with a different mouse gesture extension as well

 I fear it might be a Firefox related problem, but at the moment this is only a guess.

The steps below sometime seem to cause the problem and sometimes not:
1. Open link in new tab
2. Switch to new tab
3. Close new tab with gesture

If anyone has a reliable way to reproduce this, please let me know.

**Comment by 130R** [comment] 2020-07-03 08:49
I can actually reproduce this always, but I couldn't tell you why unfortunately. 

With "When you open a link in a new tab, switch to it immediately" set in Firefox options what I've noticed is that the state of the cursor actually gets stuck. For example:

1. Hover over a link (so cursor shows the hand icon) and use the middle mouse button to open the link in a new tab
2. Close new tab with gesture
3. On the original tab the cursor is now stuck in the hand icon state

I'm using up as the gesture to close the tab, although I can't imagine that makes any difference!

**Comment by Robbendebiene** [comment] 2020-07-03 09:17
> With "When you open a link in a new tab, switch to it immediately" set in Firefox options what I've noticed is that the state of the cursor actually gets stuck. For example:

Looks like I can reliable reproduce it now.

**Comment by shazzap** [comment] 2020-07-03 21:35
It happens to me consistently with the following steps.

1. I have a web page open.
2. I open a link on it  (right-click, open in new tab).
3. I go to the new tab.
4. I make sure one the new tab the mouse is not over a link. That is, on the new tab, **verify the mouse is the pointer arrow and not hovering over a link or anything**. 
5. Now I use a mouse gesture to close the tab and return to your previous tab.
6. The mouse pointer is not stuck with a pointer arrow even if I hover over a link. I don't see the "hand" mouse pointer. 
7. Move the mouse away off of firefox and bring it back. It is now restored.

**Comment by Robbendebiene** [comment] 2020-07-06 10:04
@shazzap Thanks for the detailed steps. However I'm still unable to reproduce it. Does this occur on any site (like this github issue)? Can someone reproduce this error using a keyboard shortcut to close the tab (ctrl + w)?

**Comment by shazzap** [comment] 2020-07-07 00:39
It happens for me on every web page including this Github page.

It's strange in that while I experience the issue with mouse gestures, I am unable to duplicate the issue via Control + W while simultaneously moving the mouse. Yet others have duplicated it using that same scenario without any mouse gestures addon installed. See this reddit thread:

https://www.reddit.com/r/firefox/comments/hllbab/firefox_78_cursor_symbol_gets_stuck_when_closing/

Something has definitely changed in 78.01 regarding the mouse. Someone has filed a bugzilla ticket regarding this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1650657

**Comment by yoasif** [comment] 2020-07-07 01:20
Per [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1650657), this is fixed in Firefox 79. You can upgrade to beta if you want the fix now.

**Comment by Robbendebiene** [comment] 2020-07-07 11:02
Thanks for the info and bugzilla ticket. Sounds like it will be fixed in the next Firefox release. Would be great if anyone can confirm that.

**Comment by 130R** [comment] 2020-07-07 13:35
I've installed 79.0b4 and can confirm it seems fixed to me. I have done very limited testing but I could reproduce this always with 78.0.1 and now I don't see the issue.  👍

**Comment by shazzap** [comment] 2020-07-07 20:52
Yes for what its worth, I just upgraded to the 79 beta and all is well again :)

**Comment by Robbendebiene** [comment] 2020-07-27 06:58
Since Firefox 79 will be released tomorrow, I'm closing this issue. Thanks for the engagement in tracking the issue down.

**Closed by Robbendebiene** 2020-07-27 06:58 UTC
Labels: external
