### ISSUE TITLE
does not work after click

### ISSUE THREAD

**Issue by nexterr** [Robbendebiene/Gesturefy#42] opened 2017-09-17 07:54 UTC
on http://4pda.ru/forum/index.php?showtopic=329398&st=21560
click https://imgur.com/a/4HseS
will open new windows http://4pda.ru/forum/index.php?showtopic=394145
gestures not work

**Comment by Robbendebiene** [comment] 2017-09-17 12:07
Which firefox and gesturefy version do you use? Are there any errors in the console after you visit the page/try to make a gesture? (you can open the console by pressing: ctrl + shift + J)

**Comment by nexterr** [comment] 2017-09-18 12:48
win32 ff 55.3  Gesturefy, Version: 1.1.8 
set new profile, install gesturefy
in  console after click https://imgur.com/a/gVo90
I made a gesture in the open page - nothing changed in the console

**Comment by Robbendebiene** [comment] 2017-09-18 13:10
Thanks for the detailed information, but this looks like a firefox bug.
Since I'm not able to reproduce the bug, maybe you can fill a bug-ticket here: https://bugzilla.mozilla.org/ ? There is also another bug which may be related to this problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1390715

**Comment by nexterr** [comment] 2017-09-18 15:53
ok, many thanks

**Comment by Robbendebiene** [comment] 2017-09-19 08:04
I finally was able to reproduce the bug so I reported it to mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1401110

**Comment by Robbendebiene** [comment] 2017-09-29 11:11
This bug should be fixed in Firefox 56. If not, please reply.

**Closed by Robbendebiene** 2017-09-29 11:11 UTC
