### ISSUE TITLE
Using Firefox Sync resets Gesturefy

### ISSUE THREAD

**Issue by grzebo** [Robbendebiene/Gesturefy#378] opened 2019-01-30 22:14 UTC
### Describe your matter in detail
Adding new instance of Firefox to Firefox Sync resets Gesturefy.

How to reproduce:
1) Install Firefox on computer A, log into Firefox Sync.
2) Install Gesturefy in Firefox on computer A.
3) Change the gestures in Gesturefy: define different gesture for closing a tab, turn off tracing of gestures etc.
4) Install Firefox on computer B, log into Firefox Sync.
5) Add-ons, bookmarks etc. get synced from Firefox on computer A to Firefox on computer B, Gesturefy gets installed in Firefox on computer B.
6) Error occurs: Gesturefy on both computer A and computer B gets reset to default setting.

### Your System
- Operating system: Kubuntu 18.04 LTS (both computers)
- Firefox version: 64.0
- Gesturefy version: 2.0.4

**Comment by Robbendebiene** [comment] 2019-01-31 22:34
Hi, since I cannot control when Firefox syncs the data, this is a common problem. Try to force Firefox to sync the data on device A before you log in on device B.
 ![grafik](https://user-images.githubusercontent.com/13716661/52090062-8a85b100-25b0-11e9-89a9-4a290e94ff07.png) 

For more finromation please visit the [troubleshooting guide](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#settings-and-gestures-get-reset-or-lost).

**Comment by grzebo** [comment] 2019-01-31 23:42
This doesn't solve the problem. Firefox on device A is fully synced, and has been like this for a long time. Device A is my day-to-day computer.

When I install Firefox on a new, clean device B (i.e. a new computer), turning on Firefox sync on the device B has the following effects:
- device B receives all the data from Firefox sync (correctly),
- device B installs all my Firefox extensions, including Gesturefy (correctly),
- Gesturefy settings on both device B **and device A** are reset to default (this is the error).

If the error would only be limited to device B not getting my Gesturefy settings - it wouldn't be so bad. But every time I sync a new Firefox instance, my main computer (device A) gets its Gesturefy settings returned to default, which is frustrating.

All my other extensions  (i.e. Ghostery, uBlock Origin, Video DownloadHelper, Tab Centrer Redux, ...) sync correctly.

It's as if sync on device B firstly installed Gesturefy, and then for some reason decided that the Gesturefy settings on device B are more recent than the ones on device A, and synced them back the other way.

**Comment by Robbendebiene** [comment] 2019-02-01 13:08
Can you tell me if also all of your configured gestures get reset?

> All my other extensions (i.e. Ghostery, uBlock Origin, Video DownloadHelper, Tab Centrer Redux, ...) sync correctly.

Do these addons also sync their settings or are they stored locally?

> It's as if sync on device B firstly installed Gesturefy, and then for some reason decided that the Gesturefy settings on device B are more recent than the ones on device A, and synced them back the other way.

Thats exaclty whats happening, I'll look into it.

**Comment by grzebo** [comment] 2019-02-01 15:08
> Do these addons also sync their settings or are they stored locally?

Ghostery and uBlock Origin sync the settings correctly, from device A to device B. Tab Center Redux doesn't sync settings (device B installs Tab Center Redux with default settings, but it doesn't reset settings on device A). I don't know about the other ones.

> I'll look into it.

Thank you!

**Comment by Robbendebiene** [comment] 2019-07-03 16:29
Should be fixed in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0) Can someone please confirm this?

**Closed** 2019-07-13 08:54 UTC

**Comment by bubblefoil** [comment] 2019-09-17 17:23
Thanks, I know I am responding way too late, anyway I have just had a chance to test this. I can confirm it works.
When I signed into Sync, Gesturify was installed with default settings. After a restart of FF, the settings was there.
Cheers.
