### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by davidp88** [Robbendebiene/Gesturefy#576] opened 2021-03-16 09:26 UTC
Add export all settings and import all,useful when moving to new PC

**Comment by Robbendebiene** [comment] 2021-03-16 10:33
This is already possible. It's hiding in the "About" section.

**Comment by Robbendebiene** [comment] 2021-03-16 10:33
Duplicate of #282

**Closed by Robbendebiene** 2021-03-16 10:33 UTC
Labels: duplicate

**Comment by davidp88** [comment] 2021-03-16 10:37
does it export all

**Comment by Robbendebiene** [comment] 2021-03-16 10:38
Yes
