### ISSUE TITLE
Can't drag the Addon to the fold menu when I customize the toolbar. 

### ISSUE THREAD

**Issue by Esirn** [Robbendebiene/Gesturefy#379] opened 2019-02-01 12:07 UTC
Sorry I can't upload the screenshot.
### System
- Operating system: Windows 7, 64bit
- Firefox version: 65.0
- Gesturefy version: 2.0.4

**Comment by Robbendebiene** [comment] 2019-02-01 12:58
There is no toolbar button for Gesturefy. You can configure it via about:addons > Settings

**Comment by Robbendebiene** [comment] 2019-02-01 12:58
Duplicate of https://github.com/Robbendebiene/Gesturefy/issues/249

**Closed** 2019-02-08 22:09 UTC
