### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by oz42** [Robbendebiene/Gesturefy#104] opened 2017-11-16 16:16 UTC
i just installed it, but I see no mouse track while doing gestures, and I cannot record new ones. Restarting browser dis not help.

**Comment by Itchiii** [comment] 2017-11-16 17:30
Do you use Mac or Linux? 
Then read the discription. 

> For MacOS & Linux users: Use left or middle mouse button due to the different right click/context menu behaviour (see this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1360278))

**Comment by oz42** [comment] 2017-11-16 17:49
I am on Linux. Thanks for the information!

**Comment by Robbendebiene** [comment] 2017-11-16 18:07
Duplicate of #1

**Closed by Robbendebiene** 2017-11-16 18:07 UTC
Labels: duplicate
